//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.VBIDE.Enums
{
	[SupportByLibrary("VBE")]
	public enum Vbext_CodePaneview
	{
		[SupportByLibrary("VBE")]
		vbext_cv_ProcedureView = 0,

		[SupportByLibrary("VBE")]
		vbext_cv_FullModuleView = 1
	}
}
