//Generated by LateBindingApi.CodeGenerator
using System;
using System.ComponentModel;
using LateBindingApi.Core;
namespace LateBindingApi.stdole
{
	[SupportByLibrary("OLE")]
	public class StdFont : Font, FontEvents_Event
	{
		#region Fields

		FontEvents_SinkHelper _sinkHelper;

		#endregion

		#region Construction

		public StdFont(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
			_sinkHelper = new FontEvents_SinkHelper(this);
		}

		public StdFont(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
			_sinkHelper = new FontEvents_SinkHelper(this);
		}

		public StdFont(COMObject replacedObject) : base(replacedObject)
		{
		}

		public StdFont()
		{
			CreateFromProgId("stdole.StdFont");
			_sinkHelper = new FontEvents_SinkHelper(this);
		}

		public StdFont(string progId)
		{
			CreateFromProgId(progId);
			_sinkHelper = new FontEvents_SinkHelper(this);
		}

		#endregion

        #region FontEvents_Event Members
        
		#pragma warning disable
		public event FontEvents_FontChangedEventHandler FontChangedEvent;

		#pragma warning restore
		
        [EditorBrowsable(EditorBrowsableState.Never), Browsable(false)]
        public bool CallEvent(string name, object[] paramArray)
        {
            Type thisType = this.GetType();

            MulticastDelegate eventDelegate = (MulticastDelegate)thisType.GetField(
												name, 
												System.Reflection.BindingFlags.Instance|
												System.Reflection.BindingFlags.NonPublic).GetValue(this);
            
            if(null!=eventDelegate)
            {            
				Delegate[] delegates = eventDelegate.GetInvocationList();
				
				foreach (Delegate invocation in delegates)
					invocation.Method.Invoke(invocation.Target, paramArray);
	                    
				return (delegates.Length > 0);
            }
            else
				return false;
        }

        [EditorBrowsable(EditorBrowsableState.Never), Browsable(false)]
        public void DisposeSinkHelper()
        {
            if (null != _sinkHelper)
			{
                _sinkHelper.Dispose();
				_sinkHelper.Dispose();
			}
        }
        
        #endregion 
	}
}
