//Generated by LateBindingApi.CodeGenerator
using System;
using System.ComponentModel;
using LateBindingApi.Core;
namespace LateBindingApi.stdole
{
	[SupportByLibrary("OLE")]
	public class StdPicture : Picture
	{
		#region Construction

		public StdPicture(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public StdPicture(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public StdPicture(COMObject replacedObject) : base(replacedObject)
		{
		}

		public StdPicture()
		{
			CreateFromProgId("stdole.StdPicture");
		}

		public StdPicture(string progId)
		{
			CreateFromProgId(progId);
		}

		#endregion


	}
}
