//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Office
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public class CalloutFormat : _IMsoDispObj
	{
		#region Construction

		public CalloutFormat(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public CalloutFormat(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public CalloutFormat(COMObject replacedObject) : base(replacedObject)
		{
		}

		public CalloutFormat()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public LateBindingApi.Office.Enums.MsoTriState Accent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Accent");
				return (LateBindingApi.Office.Enums.MsoTriState)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Accent", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public LateBindingApi.Office.Enums.MsoCalloutAngleType Angle
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Angle");
				return (LateBindingApi.Office.Enums.MsoCalloutAngleType)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Angle", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public LateBindingApi.Office.Enums.MsoTriState AutoAttach
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "AutoAttach");
				return (LateBindingApi.Office.Enums.MsoTriState)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "AutoAttach", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public LateBindingApi.Office.Enums.MsoTriState AutoLength
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "AutoLength");
				return (LateBindingApi.Office.Enums.MsoTriState)returnValue;
			}
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public LateBindingApi.Office.Enums.MsoTriState Border
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Border");
				return (LateBindingApi.Office.Enums.MsoTriState)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Border", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public Double Drop
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Drop");
				return (Double)returnValue;
			}
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public LateBindingApi.Office.Enums.MsoCalloutDropType DropType
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "DropType");
				return (LateBindingApi.Office.Enums.MsoCalloutDropType)returnValue;
			}
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public Double Gap
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Gap");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Gap", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public Double Length
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Length");
				return (Double)returnValue;
			}
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public LateBindingApi.Office.Enums.MsoCalloutType Type
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Type");
				return (LateBindingApi.Office.Enums.MsoCalloutType)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Type", value);
			}						
		}


		#endregion

		#region Methods

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public void AutomaticLength()
		{
			Invoker.Method(this, "AutomaticLength", null);
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public void CustomDrop(Double drop)
		{
			object[] paramArray = new object[1];
			paramArray[0] = drop;
			Invoker.Method(this, "CustomDrop", paramArray);
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public void CustomLength(Double length)
		{
			object[] paramArray = new object[1];
			paramArray[0] = length;
			Invoker.Method(this, "CustomLength", paramArray);
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public void PresetDrop(LateBindingApi.Office.Enums.MsoCalloutDropType dropType)
		{
			object[] paramArray = new object[1];
			paramArray[0] = dropType;
			Invoker.Method(this, "PresetDrop", paramArray);
		}

		#endregion

	}
}
