//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Office
{
	[SupportByLibrary("OF12","OF14")]
	public class IMsoAxis : COMObject
	{
		#region Construction

		public IMsoAxis(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public IMsoAxis(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public IMsoAxis(COMObject replacedObject) : base(replacedObject)
		{
		}

		public IMsoAxis()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("OF12","OF14")]
		public bool AxisBetweenCategories
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "AxisBetweenCategories");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "AxisBetweenCategories", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.XlAxisGroup AxisGroup
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "AxisGroup");
				return (LateBindingApi.Office.Enums.XlAxisGroup)returnValue;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.IMsoAxisTitle AxisTitle
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "AxisTitle");
				if(null == returnValue)
					return null;
				LateBindingApi.Office.IMsoAxisTitle newClass = new LateBindingApi.Office.IMsoAxisTitle(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public COMVariant CategoryNames
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "CategoryNames");
				COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
				return returnObject;
			}
			set
			{
				Invoker.PropertySet(this, "CategoryNames", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.XlAxisCrosses Crosses
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Crosses");
				return (LateBindingApi.Office.Enums.XlAxisCrosses)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Crosses", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public Double CrossesAt
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "CrossesAt");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "CrossesAt", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public bool HasMajorGridlines
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "HasMajorGridlines");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "HasMajorGridlines", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public bool HasMinorGridlines
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "HasMinorGridlines");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "HasMinorGridlines", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public bool HasTitle
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "HasTitle");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "HasTitle", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.GridLines MajorGridlines
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MajorGridlines");
				if(null == returnValue)
					return null;
				LateBindingApi.Office.GridLines newClass = new LateBindingApi.Office.GridLines(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.XlTickMark MajorTickMark
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MajorTickMark");
				return (LateBindingApi.Office.Enums.XlTickMark)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MajorTickMark", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public Double MajorUnit
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MajorUnit");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MajorUnit", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public Double LogBase
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "LogBase");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "LogBase", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public bool TickLabelSpacingIsAuto
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "TickLabelSpacingIsAuto");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "TickLabelSpacingIsAuto", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public bool MajorUnitIsAuto
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MajorUnitIsAuto");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MajorUnitIsAuto", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public Double MaximumScale
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MaximumScale");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MaximumScale", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public bool MaximumScaleIsAuto
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MaximumScaleIsAuto");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MaximumScaleIsAuto", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public Double MinimumScale
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MinimumScale");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MinimumScale", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public bool MinimumScaleIsAuto
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MinimumScaleIsAuto");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MinimumScaleIsAuto", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.GridLines MinorGridlines
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MinorGridlines");
				if(null == returnValue)
					return null;
				LateBindingApi.Office.GridLines newClass = new LateBindingApi.Office.GridLines(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.XlTickMark MinorTickMark
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MinorTickMark");
				return (LateBindingApi.Office.Enums.XlTickMark)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MinorTickMark", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public Double MinorUnit
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MinorUnit");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MinorUnit", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public bool MinorUnitIsAuto
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MinorUnitIsAuto");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MinorUnitIsAuto", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public bool ReversePlotOrder
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "ReversePlotOrder");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "ReversePlotOrder", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.XlScaleType ScaleType
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "ScaleType");
				return (LateBindingApi.Office.Enums.XlScaleType)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "ScaleType", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.XlTickLabelPosition TickLabelPosition
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "TickLabelPosition");
				return (LateBindingApi.Office.Enums.XlTickLabelPosition)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "TickLabelPosition", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.IMsoTickLabels TickLabels
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "TickLabels");
				if(null == returnValue)
					return null;
				LateBindingApi.Office.IMsoTickLabels newClass = new LateBindingApi.Office.IMsoTickLabels(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public Int32 TickLabelSpacing
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "TickLabelSpacing");
				return (Int32)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "TickLabelSpacing", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public Int32 TickMarkSpacing
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "TickMarkSpacing");
				return (Int32)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "TickMarkSpacing", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.XlAxisType Type
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Type");
				return (LateBindingApi.Office.Enums.XlAxisType)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Type", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.XlTimeUnit BaseUnit
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "BaseUnit");
				return (LateBindingApi.Office.Enums.XlTimeUnit)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "BaseUnit", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public bool BaseUnitIsAuto
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "BaseUnitIsAuto");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "BaseUnitIsAuto", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.XlTimeUnit MajorUnitScale
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MajorUnitScale");
				return (LateBindingApi.Office.Enums.XlTimeUnit)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MajorUnitScale", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.XlTimeUnit MinorUnitScale
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MinorUnitScale");
				return (LateBindingApi.Office.Enums.XlTimeUnit)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MinorUnitScale", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.XlCategoryType CategoryType
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "CategoryType");
				return (LateBindingApi.Office.Enums.XlCategoryType)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "CategoryType", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public Double Left
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Left");
				return (Double)returnValue;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public Double Top
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Top");
				return (Double)returnValue;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public Double Width
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Width");
				return (Double)returnValue;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public Double Height
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Height");
				return (Double)returnValue;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.XlDisplayUnit DisplayUnit
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "DisplayUnit");
				return (LateBindingApi.Office.Enums.XlDisplayUnit)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "DisplayUnit", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public Double DisplayUnitCustom
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "DisplayUnitCustom");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "DisplayUnitCustom", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public bool HasDisplayUnitLabel
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "HasDisplayUnitLabel");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "HasDisplayUnitLabel", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.IMsoDisplayUnitLabel DisplayUnitLabel
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "DisplayUnitLabel");
				if(null == returnValue)
					return null;
				LateBindingApi.Office.IMsoDisplayUnitLabel newClass = new LateBindingApi.Office.IMsoDisplayUnitLabel(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.IMsoBorder Border
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Border");
				if(null == returnValue)
					return null;
				LateBindingApi.Office.IMsoBorder newClass = new LateBindingApi.Office.IMsoBorder(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public string Name
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Name");
				return (string)returnValue;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.IMsoChartFormat Format
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Format");
				if(null == returnValue)
					return null;
				LateBindingApi.Office.IMsoChartFormat newClass = new LateBindingApi.Office.IMsoChartFormat(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("OF14")]
		public COMObject Application
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Application");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("OF14")]
		public Int32 Creator
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Creator");
				return (Int32)returnValue;
			}
		}

		[SupportByLibrary("OF14")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		#endregion

		#region Methods

		[SupportByLibrary("OF12","OF14")]
		public COMVariant Delete()
		{
			object returnValue = Invoker.MethodReturn(this, "Delete", null);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		[SupportByLibrary("OF12","OF14")]
		public COMVariant Select()
		{
			object returnValue = Invoker.MethodReturn(this, "Select", null);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		#endregion

	}
}
