//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Office
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public class LanguageSettings : _IMsoDispObj
	{
		#region Construction

		public LanguageSettings(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public LanguageSettings(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public LanguageSettings(COMObject replacedObject) : base(replacedObject)
		{
		}

		public LanguageSettings()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public Int32 get_LanguageID(LateBindingApi.Office.Enums.MsoAppLanguageID id)
		{
			object[] paramArray = new object[1];
			paramArray[0] = id;
			object returnValue = Invoker.PropertyGet(this, "LanguageID", paramArray);
			return (Int32)returnValue;
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public bool get_LanguagePreferredForEditing(LateBindingApi.Office.Enums.MsoLanguageID lid)
		{
			object[] paramArray = new object[1];
			paramArray[0] = lid;
			object returnValue = Invoker.PropertyGet(this, "LanguagePreferredForEditing", paramArray);
			return (bool)returnValue;
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		#endregion

		#region Methods

		#endregion

	}
}
