//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Office
{
	[SupportByLibrary("OF10","OF11","OF12","OF14")]
	public class NewFile : _IMsoDispObj
	{
		#region Construction

		public NewFile(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public NewFile(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public NewFile(COMObject replacedObject) : base(replacedObject)
		{
		}

		public NewFile()
		{
		}

		#endregion

		#region Properties

		#endregion

		#region Methods

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		public bool Add(string fileName)
		{
			object[] paramArray = new object[1];
			paramArray[0] = fileName;
			object returnValue = Invoker.MethodReturn(this, "Add", paramArray);
			return (bool)returnValue;
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		public bool Add(string fileName, object section, object displayName, object action)
		{
			object[] paramArray = new object[4];
			paramArray[0] = fileName;
			paramArray[1] = section;
			paramArray[2] = displayName;
			paramArray[3] = action;
			object returnValue = Invoker.MethodReturn(this, "Add", paramArray);
			return (bool)returnValue;
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		public bool Remove(string fileName)
		{
			object[] paramArray = new object[1];
			paramArray[0] = fileName;
			object returnValue = Invoker.MethodReturn(this, "Remove", paramArray);
			return (bool)returnValue;
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		public bool Remove(string fileName, object section, object displayName, object action)
		{
			object[] paramArray = new object[4];
			paramArray[0] = fileName;
			paramArray[1] = section;
			paramArray[2] = displayName;
			paramArray[3] = action;
			object returnValue = Invoker.MethodReturn(this, "Remove", paramArray);
			return (bool)returnValue;
		}

		#endregion

	}
}
