//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Office
{
	[SupportByLibrary("OF12","OF14")]
	public class ParagraphFormat2 : _IMsoDispObj
	{
		#region Construction

		public ParagraphFormat2(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public ParagraphFormat2(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public ParagraphFormat2(COMObject replacedObject) : base(replacedObject)
		{
		}

		public ParagraphFormat2()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("OF12","OF14")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.MsoParagraphAlignment Alignment
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Alignment");
				return (LateBindingApi.Office.Enums.MsoParagraphAlignment)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Alignment", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.MsoBaselineAlignment BaselineAlignment
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "BaselineAlignment");
				return (LateBindingApi.Office.Enums.MsoBaselineAlignment)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "BaselineAlignment", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.BulletFormat2 Bullet
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Bullet");
				if(null == returnValue)
					return null;
				LateBindingApi.Office.BulletFormat2 newClass = new LateBindingApi.Office.BulletFormat2(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.MsoTriState FarEastLineBreakLevel
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "FarEastLineBreakLevel");
				return (LateBindingApi.Office.Enums.MsoTriState)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "FarEastLineBreakLevel", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public Double FirstLineIndent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "FirstLineIndent");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "FirstLineIndent", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.MsoTriState HangingPunctuation
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "HangingPunctuation");
				return (LateBindingApi.Office.Enums.MsoTriState)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "HangingPunctuation", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public Int32 IndentLevel
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "IndentLevel");
				return (Int32)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "IndentLevel", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public Double LeftIndent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "LeftIndent");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "LeftIndent", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.MsoTriState LineRuleAfter
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "LineRuleAfter");
				return (LateBindingApi.Office.Enums.MsoTriState)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "LineRuleAfter", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.MsoTriState LineRuleBefore
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "LineRuleBefore");
				return (LateBindingApi.Office.Enums.MsoTriState)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "LineRuleBefore", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.MsoTriState LineRuleWithin
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "LineRuleWithin");
				return (LateBindingApi.Office.Enums.MsoTriState)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "LineRuleWithin", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public Double RightIndent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "RightIndent");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "RightIndent", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public Double SpaceAfter
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "SpaceAfter");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "SpaceAfter", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public Double SpaceBefore
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "SpaceBefore");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "SpaceBefore", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public Double SpaceWithin
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "SpaceWithin");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "SpaceWithin", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.TabStops2 TabStops
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "TabStops");
				if(null == returnValue)
					return null;
				LateBindingApi.Office.TabStops2 newClass = new LateBindingApi.Office.TabStops2(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.MsoTextDirection TextDirection
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "TextDirection");
				return (LateBindingApi.Office.Enums.MsoTextDirection)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "TextDirection", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.MsoTriState WordWrap
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "WordWrap");
				return (LateBindingApi.Office.Enums.MsoTriState)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "WordWrap", value);
			}						
		}


		#endregion

		#region Methods

		#endregion

	}
}
