//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Office
{
	[SupportByLibrary("OF12","OF14")]
	public class PolicyItem : _IMsoDispObj
	{
		#region Construction

		public PolicyItem(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public PolicyItem(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public PolicyItem(COMObject replacedObject) : base(replacedObject)
		{
		}

		public PolicyItem()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("OF12","OF14")]
		public string Id
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Id");
				return (string)returnValue;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public string Name
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Name");
				return (string)returnValue;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public string Description
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Description");
				return (string)returnValue;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public string Data
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Data");
				return (string)returnValue;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		#endregion

		#region Methods

		#endregion

	}
}
