//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Office
{
	[SupportByLibrary("OF12","OF14")]
	public class Ruler2 : _IMsoDispObj
	{
		#region Construction

		public Ruler2(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public Ruler2(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public Ruler2(COMObject replacedObject) : base(replacedObject)
		{
		}

		public Ruler2()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("OF12","OF14")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.RulerLevels2 Levels
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Levels");
				if(null == returnValue)
					return null;
				LateBindingApi.Office.RulerLevels2 newClass = new LateBindingApi.Office.RulerLevels2(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.TabStops2 TabStops
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "TabStops");
				if(null == returnValue)
					return null;
				LateBindingApi.Office.TabStops2 newClass = new LateBindingApi.Office.TabStops2(this, returnValue);
				return newClass;
			}
		}

		#endregion

		#region Methods

		#endregion

	}
}
