//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Office
{
	[SupportByLibrary("OF12","OF14")]
	public class ThemeColor : _IMsoDispObj
	{
		#region Construction

		public ThemeColor(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public ThemeColor(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public ThemeColor(COMObject replacedObject) : base(replacedObject)
		{
		}

		public ThemeColor()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("OF12","OF14")]
		public Int32 RGB
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "RGB");
				return (Int32)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "RGB", value);
			}						
		}


		[SupportByLibrary("OF12","OF14")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("OF12","OF14")]
		public LateBindingApi.Office.Enums.MsoThemeColorSchemeIndex ThemeColorSchemeIndex
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "ThemeColorSchemeIndex");
				return (LateBindingApi.Office.Enums.MsoThemeColorSchemeIndex)returnValue;
			}
		}

		#endregion

		#region Methods

		#endregion

	}
}
