//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Office
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public class WebPageFont : _IMsoDispObj
	{
		#region Construction

		public WebPageFont(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public WebPageFont(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public WebPageFont(COMObject replacedObject) : base(replacedObject)
		{
		}

		public WebPageFont()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public string ProportionalFont
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "ProportionalFont");
				return (string)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "ProportionalFont", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public Double ProportionalFontSize
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "ProportionalFontSize");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "ProportionalFontSize", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public string FixedWidthFont
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "FixedWidthFont");
				return (string)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "FixedWidthFont", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public Double FixedWidthFontSize
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "FixedWidthFontSize");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "FixedWidthFontSize", value);
			}						
		}


		#endregion

		#region Methods

		#endregion

	}
}
