//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum CertificateVerificationResults
	{
		[SupportByLibrary("OF12","OF14")]
		certverresError = 0,

		[SupportByLibrary("OF12","OF14")]
		certverresVerifying = 1,

		[SupportByLibrary("OF12","OF14")]
		certverresUnverified = 2,

		[SupportByLibrary("OF12","OF14")]
		certverresValid = 3,

		[SupportByLibrary("OF12","OF14")]
		certverresInvalid = 4,

		[SupportByLibrary("OF12","OF14")]
		certverresExpired = 5,

		[SupportByLibrary("OF12","OF14")]
		certverresRevoked = 6,

		[SupportByLibrary("OF12","OF14")]
		certverresUntrusted = 7
	}
}
