//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum ContentVerificationResults
	{
		[SupportByLibrary("OF12","OF14")]
		contverresError = 0,

		[SupportByLibrary("OF12","OF14")]
		contverresVerifying = 1,

		[SupportByLibrary("OF12","OF14")]
		contverresUnverified = 2,

		[SupportByLibrary("OF12","OF14")]
		contverresValid = 3,

		[SupportByLibrary("OF12","OF14")]
		contverresModified = 4
	}
}
