//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public enum MsoAlignCmd
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAlignLefts = 0,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAlignCenters = 1,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAlignRights = 2,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAlignTops = 3,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAlignMiddles = 4,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAlignBottoms = 5
	}
}
