//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum MsoBlogCategorySupport
	{
		[SupportByLibrary("OF12","OF14")]
		msoBlogNoCategories = 0,

		[SupportByLibrary("OF12","OF14")]
		msoBlogOneCategory = 1,

		[SupportByLibrary("OF12","OF14")]
		msoBlogMultipleCategories = 2
	}
}
