//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public enum MsoCalloutDropType
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoCalloutDropMixed = -2,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoCalloutDropCustom = 1,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoCalloutDropTop = 2,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoCalloutDropCenter = 3,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoCalloutDropBottom = 4
	}
}
