//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14")]
	public enum MsoDiagramNodeType
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoDiagramNode = 1,

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoDiagramAssistant = 2
	}
}
