//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public enum MsoEncoding
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingThai = 874,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingJapaneseShiftJIS = 932,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingSimplifiedChineseGBK = 936,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingKorean = 949,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingTraditionalChineseBig5 = 950,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingUnicodeLittleEndian = 1200,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingUnicodeBigEndian = 1201,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingCentralEuropean = 1250,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingCyrillic = 1251,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingWestern = 1252,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingGreek = 1253,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingTurkish = 1254,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingHebrew = 1255,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingArabic = 1256,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingBaltic = 1257,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingVietnamese = 1258,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingAutoDetect = 50001,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingJapaneseAutoDetect = 50932,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingSimplifiedChineseAutoDetect = 50936,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingKoreanAutoDetect = 50949,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingTraditionalChineseAutoDetect = 50950,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingCyrillicAutoDetect = 51251,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingGreekAutoDetect = 51253,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingArabicAutoDetect = 51256,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingISO88591Latin1 = 28591,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingISO88592CentralEurope = 28592,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingISO88593Latin3 = 28593,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingISO88594Baltic = 28594,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingISO88595Cyrillic = 28595,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingISO88596Arabic = 28596,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingISO88597Greek = 28597,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingISO88598Hebrew = 28598,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingISO88599Turkish = 28599,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingISO885915Latin9 = 28605,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingISO2022JPNoHalfwidthKatakana = 50220,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingISO2022JPJISX02021984 = 50221,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingISO2022JPJISX02011989 = 50222,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingISO2022KR = 50225,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingISO2022CNTraditionalChinese = 50227,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingISO2022CNSimplifiedChinese = 50229,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingMacRoman = 10000,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingMacJapanese = 10001,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingMacTraditionalChineseBig5 = 10002,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingMacKorean = 10003,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingMacArabic = 10004,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingMacHebrew = 10005,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingMacGreek1 = 10006,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingMacCyrillic = 10007,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingMacSimplifiedChineseGB2312 = 10008,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingMacRomania = 10010,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingMacUkraine = 10017,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingMacLatin2 = 10029,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingMacIcelandic = 10079,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingMacTurkish = 10081,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingMacCroatia = 10082,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICUSCanada = 37,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICInternational = 500,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICMultilingualROECELatin2 = 870,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICGreekModern = 875,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICTurkishLatin5 = 1026,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICGermany = 20273,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICDenmarkNorway = 20277,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICFinlandSweden = 20278,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICItaly = 20280,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICLatinAmericaSpain = 20284,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICUnitedKingdom = 20285,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICJapaneseKatakanaExtended = 20290,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICFrance = 20297,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICArabic = 20420,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICGreek = 20423,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICHebrew = 20424,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICKoreanExtended = 20833,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICThai = 20838,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICIcelandic = 20871,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICTurkish = 20905,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICRussian = 20880,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICSerbianBulgarian = 21025,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICJapaneseKatakanaExtendedAndJapanese = 50930,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICKoreanExtendedAndKorean = 50933,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICSimplifiedChineseExtendedAndSimplifiedChinese = 50935,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICUSCanadaAndTraditionalChinese = 50937,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEBCDICJapaneseLatinExtendedAndJapanese = 50939,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingOEMUnitedStates = 437,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingOEMGreek437G = 737,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingOEMBaltic = 775,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingOEMMultilingualLatinI = 850,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingOEMMultilingualLatinII = 852,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingOEMCyrillic = 855,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingOEMTurkish = 857,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingOEMPortuguese = 860,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingOEMIcelandic = 861,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingOEMHebrew = 862,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingOEMCanadianFrench = 863,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingOEMArabic = 864,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingOEMNordic = 865,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingOEMCyrillicII = 866,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingOEMModernGreek = 869,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEUCJapanese = 51932,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEUCChineseSimplifiedChinese = 51936,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEUCKorean = 51949,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEUCTaiwaneseTraditionalChinese = 51950,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingArabicASMO = 708,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingArabicTransparentASMO = 720,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingKoreanJohab = 1361,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingTaiwanCNS = 20000,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingTaiwanTCA = 20001,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingTaiwanEten = 20002,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingTaiwanIBM5550 = 20003,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingTaiwanTeleText = 20004,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingTaiwanWang = 20005,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingIA5IRV = 20105,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingIA5German = 20106,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingIA5Swedish = 20107,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingIA5Norwegian = 20108,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingUSASCII = 20127,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingT61 = 20261,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingISO6937NonSpacingAccent = 20269,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingKOI8R = 20866,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingExtAlphaLowercase = 21027,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingKOI8U = 21866,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingEuropa3 = 29001,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingHZGBSimplifiedChinese = 52936,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingUTF7 = 65000,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEncodingUTF8 = 65001,

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoEncodingEBCDICUSCanadaAndJapanese = 50931,

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoEncodingISCIIDevanagari = 57002,

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoEncodingISCIIBengali = 57003,

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoEncodingISCIITamil = 57004,

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoEncodingISCIITelugu = 57005,

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoEncodingISCIIAssamese = 57006,

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoEncodingISCIIOriya = 57007,

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoEncodingISCIIKannada = 57008,

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoEncodingISCIIMalayalam = 57009,

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoEncodingISCIIGujarati = 57010,

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoEncodingISCIIPunjabi = 57011,

		[SupportByLibrary("OF11","OF12","OF14")]
		msoEncodingISO88598HebrewLogical = 38598,

		[SupportByLibrary("OF11","OF12","OF14")]
		msoEncodingSimplifiedChineseGB18030 = 54936
	}
}
