//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public enum MsoFileFindListBy
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoListbyName = 1,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoListbyTitle = 2
	}
}
