//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public enum MsoLastModified
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoLastModifiedYesterday = 1,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoLastModifiedToday = 2,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoLastModifiedLastWeek = 3,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoLastModifiedThisWeek = 4,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoLastModifiedLastMonth = 5,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoLastModifiedThisMonth = 6,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoLastModifiedAnyTime = 7
	}
}
