//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public enum MsoLineDashStyle
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoLineDashStyleMixed = -2,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoLineSolid = 1,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoLineSquareDot = 2,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoLineRoundDot = 3,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoLineDash = 4,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoLineDashDot = 5,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoLineDashDotDot = 6,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoLineLongDash = 7,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoLineLongDashDot = 8,

		[SupportByLibrary("OF12","OF14")]
		msoLineLongDashDotDot = 9,

		[SupportByLibrary("OF12","OF14")]
		msoLineSysDash = 10,

		[SupportByLibrary("OF12","OF14")]
		msoLineSysDot = 11,

		[SupportByLibrary("OF12","OF14")]
		msoLineSysDashDot = 12
	}
}
