//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public enum MsoPictureColorType
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoPictureMixed = -2,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoPictureAutomatic = 1,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoPictureGrayscale = 2,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoPictureBlackAndWhite = 3,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoPictureWatermark = 4
	}
}
