//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF11","OF12","OF14")]
	public enum MsoSyncVersionType
	{
		[SupportByLibrary("OF11","OF12","OF14")]
		msoSyncVersionLastViewed = 0,

		[SupportByLibrary("OF11","OF12","OF14")]
		msoSyncVersionServer = 1
	}
}
