//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public enum MsoSortOrder
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoSortOrderAscending = 1,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoSortOrderDescending = 2
	}
}
