//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public enum MsoTextureType
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoTextureTypeMixed = -2,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoTexturePreset = 1,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoTextureUserDefined = 2
	}
}
