//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum MsoTextChangeCase
	{
		[SupportByLibrary("OF12","OF14")]
		msoCaseSentence = 1,

		[SupportByLibrary("OF12","OF14")]
		msoCaseLower = 2,

		[SupportByLibrary("OF12","OF14")]
		msoCaseUpper = 3,

		[SupportByLibrary("OF12","OF14")]
		msoCaseTitle = 4,

		[SupportByLibrary("OF12","OF14")]
		msoCaseToggle = 5
	}
}
