//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public enum MsoTriState
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoTrue = -1,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoFalse = 0,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoCTrue = 1,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoTriStateToggle = -3,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoTriStateMixed = -2
	}
}
