//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum MsoTextStrike
	{
		[SupportByLibrary("OF12","OF14")]
		msoStrikeMixed = -2,

		[SupportByLibrary("OF12","OF14")]
		msoNoStrike = 0,

		[SupportByLibrary("OF12","OF14")]
		msoSingleStrike = 1,

		[SupportByLibrary("OF12","OF14")]
		msoDoubleStrike = 2
	}
}
