//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public enum MsoWizardActType
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoWizardActInactive = 0,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoWizardActActive = 1,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoWizardActSuspend = 2,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoWizardActResume = 3
	}
}
