//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum XlAxisType
	{
		[SupportByLibrary("OF12","OF14")]
		xlCategory = 1,

		[SupportByLibrary("OF12","OF14")]
		xlSeriesAxis = 3,

		[SupportByLibrary("OF12","OF14")]
		xlValue = 2
	}
}
