//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum XlCategoryType
	{
		[SupportByLibrary("OF12","OF14")]
		xlCategoryScale = 2,

		[SupportByLibrary("OF12","OF14")]
		xlTimeScale = 3,

		[SupportByLibrary("OF12","OF14")]
		xlAutomaticScale = -4105
	}
}
