//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum XlConstants
	{
		[SupportByLibrary("OF12","OF14")]
		xlAutomatic = -4105,

		[SupportByLibrary("OF12","OF14")]
		xlCombination = -4111,

		[SupportByLibrary("OF12","OF14")]
		xlCustom = -4114,

		[SupportByLibrary("OF12","OF14")]
		xlBar = 2,

		[SupportByLibrary("OF12","OF14")]
		xlColumn = 3,

		[SupportByLibrary("OF12","OF14")]
		xl3DBar = -4099,

		[SupportByLibrary("OF12","OF14")]
		xl3DSurface = -4103,

		[SupportByLibrary("OF12","OF14")]
		xlDefaultAutoFormat = -1,

		[SupportByLibrary("OF12","OF14")]
		xlNone = -4142,

		[SupportByLibrary("OF14")]
		xlAbove = 0,

		[SupportByLibrary("OF14")]
		xlBelow = 1,

		[SupportByLibrary("OF14")]
		xlBoth = 1,

		[SupportByLibrary("OF14")]
		xlBottom = -4107,

		[SupportByLibrary("OF14")]
		xlCenter = -4108,

		[SupportByLibrary("OF14")]
		xlChecker = 9,

		[SupportByLibrary("OF14")]
		xlCircle = 8,

		[SupportByLibrary("OF14")]
		xlCorner = 2,

		[SupportByLibrary("OF14")]
		xlCrissCross = 16,

		[SupportByLibrary("OF14")]
		xlCross = 4,

		[SupportByLibrary("OF14")]
		xlDiamond = 2,

		[SupportByLibrary("OF14")]
		xlDistributed = -4117,

		[SupportByLibrary("OF14")]
		xlFill = 5,

		[SupportByLibrary("OF14")]
		xlFixedValue = 1,

		[SupportByLibrary("OF14")]
		xlGeneral = 1,

		[SupportByLibrary("OF14")]
		xlGray16 = 17,

		[SupportByLibrary("OF14")]
		xlGray25 = -4124,

		[SupportByLibrary("OF14")]
		xlGray50 = -4125,

		[SupportByLibrary("OF14")]
		xlGray75 = -4126,

		[SupportByLibrary("OF14")]
		xlGray8 = 18,

		[SupportByLibrary("OF14")]
		xlGrid = 15,

		[SupportByLibrary("OF14")]
		xlHigh = -4127,

		[SupportByLibrary("OF14")]
		xlInside = 2,

		[SupportByLibrary("OF14")]
		xlJustify = -4130,

		[SupportByLibrary("OF14")]
		xlLeft = -4131,

		[SupportByLibrary("OF14")]
		xlLightDown = 13,

		[SupportByLibrary("OF14")]
		xlLightHorizontal = 11,

		[SupportByLibrary("OF14")]
		xlLightUp = 14,

		[SupportByLibrary("OF14")]
		xlLightVertical = 12,

		[SupportByLibrary("OF14")]
		xlLow = -4134,

		[SupportByLibrary("OF14")]
		xlMaximum = 2,

		[SupportByLibrary("OF14")]
		xlMinimum = 4,

		[SupportByLibrary("OF14")]
		xlMinusValues = 3,

		[SupportByLibrary("OF14")]
		xlNextToAxis = 4,

		[SupportByLibrary("OF14")]
		xlOpaque = 3,

		[SupportByLibrary("OF14")]
		xlOutside = 3,

		[SupportByLibrary("OF14")]
		xlPercent = 2,

		[SupportByLibrary("OF14")]
		xlPlus = 9,

		[SupportByLibrary("OF14")]
		xlPlusValues = 2,

		[SupportByLibrary("OF14")]
		xlRight = -4152,

		[SupportByLibrary("OF14")]
		xlScale = 3,

		[SupportByLibrary("OF14")]
		xlSemiGray75 = 10,

		[SupportByLibrary("OF14")]
		xlShowLabel = 4,

		[SupportByLibrary("OF14")]
		xlShowLabelAndPercent = 5,

		[SupportByLibrary("OF14")]
		xlShowPercent = 3,

		[SupportByLibrary("OF14")]
		xlShowValue = 2,

		[SupportByLibrary("OF14")]
		xlSingle = 2,

		[SupportByLibrary("OF14")]
		xlSolid = 1,

		[SupportByLibrary("OF14")]
		xlSquare = 1,

		[SupportByLibrary("OF14")]
		xlStar = 5,

		[SupportByLibrary("OF14")]
		xlStError = 4,

		[SupportByLibrary("OF14")]
		xlTop = -4160,

		[SupportByLibrary("OF14")]
		xlTransparent = 2,

		[SupportByLibrary("OF14")]
		xlTriangle = 3
	}
}
