//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum XlDataLabelPosition
	{
		[SupportByLibrary("OF12","OF14")]
		xlLabelPositionCenter = -4108,

		[SupportByLibrary("OF12","OF14")]
		xlLabelPositionAbove = 0,

		[SupportByLibrary("OF12","OF14")]
		xlLabelPositionBelow = 1,

		[SupportByLibrary("OF12","OF14")]
		xlLabelPositionLeft = -4131,

		[SupportByLibrary("OF12","OF14")]
		xlLabelPositionRight = -4152,

		[SupportByLibrary("OF12","OF14")]
		xlLabelPositionOutsideEnd = 2,

		[SupportByLibrary("OF12","OF14")]
		xlLabelPositionInsideEnd = 3,

		[SupportByLibrary("OF12","OF14")]
		xlLabelPositionInsideBase = 4,

		[SupportByLibrary("OF12","OF14")]
		xlLabelPositionBestFit = 5,

		[SupportByLibrary("OF12","OF14")]
		xlLabelPositionMixed = 6,

		[SupportByLibrary("OF12","OF14")]
		xlLabelPositionCustom = 7
	}
}
