//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum XlDisplayBlanksAs
	{
		[SupportByLibrary("OF12","OF14")]
		xlInterpolated = 3,

		[SupportByLibrary("OF12","OF14")]
		xlNotPlotted = 1,

		[SupportByLibrary("OF12","OF14")]
		xlZero = 2
	}
}
