//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum XlMarkerStyle
	{
		[SupportByLibrary("OF12","OF14")]
		xlMarkerStyleAutomatic = -4105,

		[SupportByLibrary("OF12","OF14")]
		xlMarkerStyleCircle = 8,

		[SupportByLibrary("OF12","OF14")]
		xlMarkerStyleDash = -4115,

		[SupportByLibrary("OF12","OF14")]
		xlMarkerStyleDiamond = 2,

		[SupportByLibrary("OF12","OF14")]
		xlMarkerStyleDot = -4118,

		[SupportByLibrary("OF12","OF14")]
		xlMarkerStyleNone = -4142,

		[SupportByLibrary("OF12","OF14")]
		xlMarkerStylePicture = -4147,

		[SupportByLibrary("OF12","OF14")]
		xlMarkerStylePlus = 9,

		[SupportByLibrary("OF12","OF14")]
		xlMarkerStyleSquare = 1,

		[SupportByLibrary("OF12","OF14")]
		xlMarkerStyleStar = 5,

		[SupportByLibrary("OF12","OF14")]
		xlMarkerStyleTriangle = 3,

		[SupportByLibrary("OF12","OF14")]
		xlMarkerStyleX = -4168
	}
}
