//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum XlVAlign
	{
		[SupportByLibrary("OF12","OF14")]
		xlVAlignBottom = -4107,

		[SupportByLibrary("OF12","OF14")]
		xlVAlignCenter = -4108,

		[SupportByLibrary("OF12","OF14")]
		xlVAlignDistributed = -4117,

		[SupportByLibrary("OF12","OF14")]
		xlVAlignJustify = -4130,

		[SupportByLibrary("OF12","OF14")]
		xlVAlignTop = -4160
	}
}
