//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.VBIDE
{
	[SupportByLibrary("VBE")]
	public class _dispVBComponentsEvents : COMObject
	{
		#region Construction

		public _dispVBComponentsEvents(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public _dispVBComponentsEvents(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public _dispVBComponentsEvents(COMObject replacedObject) : base(replacedObject)
		{
		}

		public _dispVBComponentsEvents()
		{
		}

		#endregion

		#region Properties

		#endregion

		#region Methods

		[SupportByLibrary("VBE")]
		public void ItemAdded(LateBindingApi.VBIDE.VBComponent vBComponent)
		{
			object[] paramArray = new object[1];
			paramArray.SetValue(vBComponent,0);
			Invoker.Method(this, "ItemAdded", paramArray);
		}

		[SupportByLibrary("VBE")]
		public void ItemRemoved(LateBindingApi.VBIDE.VBComponent vBComponent)
		{
			object[] paramArray = new object[1];
			paramArray.SetValue(vBComponent,0);
			Invoker.Method(this, "ItemRemoved", paramArray);
		}

		[SupportByLibrary("VBE")]
		public void ItemRenamed(LateBindingApi.VBIDE.VBComponent vBComponent, string oldName)
		{
			object[] paramArray = new object[2];
			paramArray.SetValue(vBComponent,0);
			paramArray[1] = oldName;
			Invoker.Method(this, "ItemRenamed", paramArray);
		}

		[SupportByLibrary("VBE")]
		public void ItemSelected(LateBindingApi.VBIDE.VBComponent vBComponent)
		{
			object[] paramArray = new object[1];
			paramArray.SetValue(vBComponent,0);
			Invoker.Method(this, "ItemSelected", paramArray);
		}

		[SupportByLibrary("VBE")]
		public void ItemActivated(LateBindingApi.VBIDE.VBComponent vBComponent)
		{
			object[] paramArray = new object[1];
			paramArray.SetValue(vBComponent,0);
			Invoker.Method(this, "ItemActivated", paramArray);
		}

		[SupportByLibrary("VBE")]
		public void ItemReloaded(LateBindingApi.VBIDE.VBComponent vBComponent)
		{
			object[] paramArray = new object[1];
			paramArray.SetValue(vBComponent,0);
			Invoker.Method(this, "ItemReloaded", paramArray);
		}

		#endregion

	}
}
