//Generated by LateBindingApi.CodeGenerator
using System;
using System.ComponentModel;
using LateBindingApi.Core;
namespace LateBindingApi.VBIDE
{
	[SupportByLibrary("VBE")]
	public class LinkedWindows : _LinkedWindows
	{
		#region Construction

		public LinkedWindows(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public LinkedWindows(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public LinkedWindows(COMObject replacedObject) : base(replacedObject)
		{
		}

		public LinkedWindows()
		{
			CreateFromProgId("VBIDE.LinkedWindows");
		}

		public LinkedWindows(string progId)
		{
			CreateFromProgId(progId);
		}

		#endregion


	}
}
