//Generated by LateBindingApi.CodeGenerator
using System;
using System.ComponentModel;
using LateBindingApi.Core;
namespace LateBindingApi.VBIDE
{
	[SupportByLibrary("VBE")]
	public class ReferencesEvents : _ReferencesEvents, _dispReferencesEvents_Event
	{
		#region Fields

		_dispReferencesEvents_SinkHelper _sinkHelper;

		#endregion

		#region Construction

		public ReferencesEvents(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
			_sinkHelper = new _dispReferencesEvents_SinkHelper(this);
		}

		public ReferencesEvents(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
			_sinkHelper = new _dispReferencesEvents_SinkHelper(this);
		}

		public ReferencesEvents(COMObject replacedObject) : base(replacedObject)
		{
		}

		public ReferencesEvents()
		{
			CreateFromProgId("VBIDE.ReferencesEvents");
			_sinkHelper = new _dispReferencesEvents_SinkHelper(this);
		}

		public ReferencesEvents(string progId)
		{
			CreateFromProgId(progId);
			_sinkHelper = new _dispReferencesEvents_SinkHelper(this);
		}

		#endregion

        #region _dispReferencesEvents_Event Members
        
		#pragma warning disable
		public event _dispReferencesEvents_ItemAddedEventHandler ItemAddedEvent;
		public event _dispReferencesEvents_ItemRemovedEventHandler ItemRemovedEvent;

		#pragma warning restore
		
        [EditorBrowsable(EditorBrowsableState.Never), Browsable(false)]
        public bool CallEvent(string name, object[] paramArray)
        {
            Type thisType = this.GetType();

            MulticastDelegate eventDelegate = (MulticastDelegate)thisType.GetField(
												name, 
												System.Reflection.BindingFlags.Instance|
												System.Reflection.BindingFlags.NonPublic).GetValue(this);
            
            if(null!=eventDelegate)
            {            
				Delegate[] delegates = eventDelegate.GetInvocationList();
				
				foreach (Delegate invocation in delegates)
					invocation.Method.Invoke(invocation.Target, paramArray);
	                    
				return (delegates.Length > 0);
            }
            else
				return false;
        }

        [EditorBrowsable(EditorBrowsableState.Never), Browsable(false)]
        public void DisposeSinkHelper()
        {
            if (null != _sinkHelper)
			{
                _sinkHelper.Dispose();
				_sinkHelper.Dispose();
			}
        }
        
        #endregion 
	}
}
