//Generated by LateBindingApi.CodeGenerator
using System;
using System.ComponentModel;
using LateBindingApi.Core;
namespace LateBindingApi.Office
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public class CommandBarButton : _CommandBarButton, _CommandBarButtonEvents_Event
	{
		#region Fields

		_CommandBarButtonEvents_SinkHelper _sinkHelper;

		#endregion

		#region Construction

		public CommandBarButton(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
			_sinkHelper = new _CommandBarButtonEvents_SinkHelper(this);
		}

		public CommandBarButton(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
			_sinkHelper = new _CommandBarButtonEvents_SinkHelper(this);
		}

		public CommandBarButton(COMObject replacedObject) : base(replacedObject)
		{
		}

		public CommandBarButton()
		{
			CreateFromProgId("Office.CommandBarButton");
			_sinkHelper = new _CommandBarButtonEvents_SinkHelper(this);
		}

		public CommandBarButton(string progId)
		{
			CreateFromProgId(progId);
			_sinkHelper = new _CommandBarButtonEvents_SinkHelper(this);
		}

		#endregion

        #region _CommandBarButtonEvents_Event Members
        
		#pragma warning disable

		public event _CommandBarButtonEvents_ClickEventHandler ClickEvent;

		#pragma warning restore
		
        [EditorBrowsable(EditorBrowsableState.Never), Browsable(false)]
        public bool CallEvent(string name, object[] paramArray)
        {
            Type thisType = this.GetType();

            MulticastDelegate eventDelegate = (MulticastDelegate)thisType.GetField(
												name, 
												System.Reflection.BindingFlags.Instance|
												System.Reflection.BindingFlags.NonPublic).GetValue(this);
            
            if(null!=eventDelegate)
            {            
				Delegate[] delegates = eventDelegate.GetInvocationList();
				
				foreach (Delegate invocation in delegates)
					invocation.Method.Invoke(invocation.Target, paramArray);
	                    
				return (delegates.Length > 0);
            }
            else
				return false;
        }

        [EditorBrowsable(EditorBrowsableState.Never), Browsable(false)]
        public void DisposeSinkHelper()
        {
            if (null != _sinkHelper)
			{
                _sinkHelper.Dispose();
				_sinkHelper.Dispose();
			}
        }
        
        #endregion 
	}
}
