//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Office
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public class CommandBar : _IMsoOleAccDispObj
	{
		#region Construction

		public CommandBar(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public CommandBar(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public CommandBar(COMObject replacedObject) : base(replacedObject)
		{
		}

		public CommandBar()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public bool BuiltIn
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "BuiltIn");
				return (bool)returnValue;
			}
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public string Context
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Context");
				return (string)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Context", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public LateBindingApi.Office.CommandBarControls Controls
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Controls");
				if(null == returnValue)
					return null;
				LateBindingApi.Office.CommandBarControls newClass = new LateBindingApi.Office.CommandBarControls(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public bool Enabled
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Enabled");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Enabled", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public Int32 Height
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Height");
				return (Int32)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Height", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public Int32 Index
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Index");
				return (Int32)returnValue;
			}
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public Int32 InstanceId
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "InstanceId");
				return (Int32)returnValue;
			}
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public Int32 Left
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Left");
				return (Int32)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Left", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public string Name
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Name");
				return (string)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Name", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public string NameLocal
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "NameLocal");
				return (string)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "NameLocal", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public LateBindingApi.Office.Enums.MsoBarPosition Position
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Position");
				return (LateBindingApi.Office.Enums.MsoBarPosition)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Position", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public Int32 RowIndex
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "RowIndex");
				return (Int32)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "RowIndex", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public LateBindingApi.Office.Enums.MsoBarProtection Protection
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Protection");
				return (LateBindingApi.Office.Enums.MsoBarProtection)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Protection", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public Int32 Top
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Top");
				return (Int32)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Top", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public LateBindingApi.Office.Enums.MsoBarType Type
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Type");
				return (LateBindingApi.Office.Enums.MsoBarType)returnValue;
			}
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public bool Visible
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Visible");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Visible", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public Int32 Width
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Width");
				return (Int32)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Width", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public bool AdaptiveMenu
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "AdaptiveMenu");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "AdaptiveMenu", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		public Int32 Id
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Id");
				return (Int32)returnValue;
			}
		}

		[SupportByLibrary("OF14")]
		public COMVariant InstanceIdPtr
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "InstanceIdPtr");
				COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		#endregion

		#region Methods

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public void Delete()
		{
			Invoker.Method(this, "Delete", null);
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public LateBindingApi.Office.CommandBarControl FindControl()
		{
			object returnValue = Invoker.MethodReturn(this, "FindControl", null);
			if(null == returnValue)
				return null;
			LateBindingApi.Office.CommandBarControl newClass = new LateBindingApi.Office.CommandBarControl(this, returnValue);
			return newClass;
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public LateBindingApi.Office.CommandBarControl FindControl(object type, object id, object tag, object visible, object recursive)
		{
			object[] paramArray = new object[5];
			paramArray[0] = type;
			paramArray[1] = id;
			paramArray[2] = tag;
			paramArray[3] = visible;
			paramArray[4] = recursive;
			object returnValue = Invoker.MethodReturn(this, "FindControl", paramArray);
			if(null == returnValue)
				return null;
			LateBindingApi.Office.CommandBarControl newClass = new LateBindingApi.Office.CommandBarControl(this, returnValue);
			return newClass;
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public void Reset()
		{
			Invoker.Method(this, "Reset", null);
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public void ShowPopup()
		{
			Invoker.Method(this, "ShowPopup", null);
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public void ShowPopup(object x, object y)
		{
			object[] paramArray = new object[2];
			paramArray[0] = x;
			paramArray[1] = y;
			Invoker.Method(this, "ShowPopup", paramArray);
		}

		#endregion

	}
}
