//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Office
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public class IAccessible : COMObject
	{
		#region Construction

		public IAccessible(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public IAccessible(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public IAccessible(COMObject replacedObject) : base(replacedObject)
		{
		}

		public IAccessible()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public COMObject accParent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "accParent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public Int32 accChildCount
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "accChildCount");
				return (Int32)returnValue;
			}
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public COMObject get_accChild(object varChild)
		{
			object[] paramArray = new object[1];
			paramArray[0] = varChild;
			object returnValue = Invoker.PropertyGet(this, "accChild", paramArray);
			COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
			return returnObject;
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public string accName
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "accName", null);
				return (string)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "accName", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public string get_accName(object varChild)
		{
			object[] paramArray = new object[1];
			paramArray[0] = varChild;
				object returnValue = Invoker.PropertyGet(this, "accName", paramArray);
				return (string)returnValue;
		}
		
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public void set_accName(object varChild, object value)
		{
			object[] paramArray = new object[1];
			paramArray[0] = varChild;
			Invoker.PropertySet(this, "accName", paramArray, value);
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public string accValue
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "accValue", null);
				return (string)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "accValue", value);
			}						
		}


		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public string get_accValue(object varChild)
		{
			object[] paramArray = new object[1];
			paramArray[0] = varChild;
				object returnValue = Invoker.PropertyGet(this, "accValue", paramArray);
				return (string)returnValue;
		}
		
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public void set_accValue(object varChild, object value)
		{
			object[] paramArray = new object[1];
			paramArray[0] = varChild;
			Invoker.PropertySet(this, "accValue", paramArray, value);
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public string accDescription
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "accDescription", null);
				return (string)returnValue;
			}
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public string get_accDescription(object varChild)
		{
			object[] paramArray = new object[1];
			paramArray[0] = varChild;
			object returnValue = Invoker.PropertyGet(this, "accDescription", paramArray);
			return (string)returnValue;
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public COMVariant accRole
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "accRole", null);
				COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public COMVariant get_accRole(object varChild)
		{
			object[] paramArray = new object[1];
			paramArray[0] = varChild;
			object returnValue = Invoker.PropertyGet(this, "accRole", paramArray);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public COMVariant accState
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "accState", null);
				COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public COMVariant get_accState(object varChild)
		{
			object[] paramArray = new object[1];
			paramArray[0] = varChild;
			object returnValue = Invoker.PropertyGet(this, "accState", paramArray);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public string accHelp
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "accHelp", null);
				return (string)returnValue;
			}
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public string get_accHelp(object varChild)
		{
			object[] paramArray = new object[1];
			paramArray[0] = varChild;
			object returnValue = Invoker.PropertyGet(this, "accHelp", paramArray);
			return (string)returnValue;
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public Int32 get_accHelpTopic(string pszHelpFile)
		{
			object[] paramArray = new object[1];
			paramArray[0] = pszHelpFile;
			object returnValue = Invoker.PropertyGet(this, "accHelpTopic", paramArray);
			return (Int32)returnValue;
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public Int32 get_accHelpTopic(string pszHelpFile, object varChild)
		{
			object[] paramArray = new object[2];
			paramArray[0] = pszHelpFile;
			paramArray[1] = varChild;
			object returnValue = Invoker.PropertyGet(this, "accHelpTopic", paramArray);
			return (Int32)returnValue;
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public string accKeyboardShortcut
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "accKeyboardShortcut", null);
				return (string)returnValue;
			}
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public string get_accKeyboardShortcut(object varChild)
		{
			object[] paramArray = new object[1];
			paramArray[0] = varChild;
			object returnValue = Invoker.PropertyGet(this, "accKeyboardShortcut", paramArray);
			return (string)returnValue;
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public COMVariant accFocus
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "accFocus");
				COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public COMVariant accSelection
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "accSelection");
				COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public string accDefaultAction
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "accDefaultAction", null);
				return (string)returnValue;
			}
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public string get_accDefaultAction(object varChild)
		{
			object[] paramArray = new object[1];
			paramArray[0] = varChild;
			object returnValue = Invoker.PropertyGet(this, "accDefaultAction", paramArray);
			return (string)returnValue;
		}

		#endregion

		#region Methods

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public void accSelect(Int32 flagsSelect)
		{
			object[] paramArray = new object[1];
			paramArray[0] = flagsSelect;
			Invoker.Method(this, "accSelect", paramArray);
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public void accSelect(Int32 flagsSelect, object varChild)
		{
			object[] paramArray = new object[2];
			paramArray[0] = flagsSelect;
			paramArray[1] = varChild;
			Invoker.Method(this, "accSelect", paramArray);
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public void accLocation(Int32 pxLeft, Int32 pyTop, Int32 pcxWidth, Int32 pcyHeight)
		{
			object[] paramArray = new object[4];
			paramArray.SetValue(pxLeft,0);
			paramArray.SetValue(pyTop,1);
			paramArray.SetValue(pcxWidth,2);
			paramArray.SetValue(pcyHeight,3);
			Invoker.Method(this, "accLocation", paramArray);
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public void accLocation(Int32 pxLeft, Int32 pyTop, Int32 pcxWidth, Int32 pcyHeight, object varChild)
		{
			object[] paramArray = new object[5];
			paramArray.SetValue(pxLeft,0);
			paramArray.SetValue(pyTop,1);
			paramArray.SetValue(pcxWidth,2);
			paramArray.SetValue(pcyHeight,3);
			paramArray[4] = varChild;
			Invoker.Method(this, "accLocation", paramArray);
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public COMVariant accNavigate(Int32 navDir)
		{
			object[] paramArray = new object[1];
			paramArray[0] = navDir;
			object returnValue = Invoker.MethodReturn(this, "accNavigate", paramArray);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public COMVariant accNavigate(Int32 navDir, object varStart)
		{
			object[] paramArray = new object[2];
			paramArray[0] = navDir;
			paramArray[1] = varStart;
			object returnValue = Invoker.MethodReturn(this, "accNavigate", paramArray);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public COMVariant accHitTest(Int32 xLeft, Int32 yTop)
		{
			object[] paramArray = new object[2];
			paramArray[0] = xLeft;
			paramArray[1] = yTop;
			object returnValue = Invoker.MethodReturn(this, "accHitTest", paramArray);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public void accDoDefaultAction()
		{
			Invoker.Method(this, "accDoDefaultAction", null);
		}

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		public void accDoDefaultAction(object varChild)
		{
			object[] paramArray = new object[1];
			paramArray[0] = varChild;
			Invoker.Method(this, "accDoDefaultAction", paramArray);
		}

		#endregion

	}
}
