//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlCategoryType
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlCategoryScale = 2,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlTimeScale = 3,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlAutomaticScale = -4105
	}
}
