//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14")]
	public enum XlCalculatedMemberType
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlCalculatedMember = 0,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlCalculatedSet = 1
	}
}
