//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlChartLocation
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlLocationAsNewSheet = 1,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlLocationAsObject = 2,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlLocationAutomatic = 3
	}
}
