//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlCommandUnderlines
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlCommandUnderlinesAutomatic = -4105,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlCommandUnderlinesOff = -4146,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlCommandUnderlinesOn = 1
	}
}
