//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlColorIndex
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlColorIndexAutomatic = -4105,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlColorIndexNone = -4142
	}
}
