//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlCutCopyMode
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlCopy = 1,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlCut = 2
	}
}
