//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL14")]
	public enum XlDataBarBorderType
	{
		[SupportByLibrary("XL14")]
		xlDataBarBorderNone = 0,

		[SupportByLibrary("XL14")]
		xlDataBarBorderSolid = 1
	}
}
