//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlFormulaLabel
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlNoLabels = -4142,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlRowLabels = 1,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlColumnLabels = 2,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlMixedLabels = 3
	}
}
