//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL12","XL14")]
	public enum XlGradientFillType
	{
		[SupportByLibrary("XL12","XL14")]
		xlGradientFillLinear = 0,

		[SupportByLibrary("XL12","XL14")]
		xlGradientFillPath = 1
	}
}
