//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL12","XL14")]
	public enum XlIconSet
	{
		[SupportByLibrary("XL12","XL14")]
		xl3Arrows = 1,

		[SupportByLibrary("XL12","XL14")]
		xl3ArrowsGray = 2,

		[SupportByLibrary("XL12","XL14")]
		xl3Flags = 3,

		[SupportByLibrary("XL12","XL14")]
		xl3TrafficLights1 = 4,

		[SupportByLibrary("XL12","XL14")]
		xl3TrafficLights2 = 5,

		[SupportByLibrary("XL12","XL14")]
		xl3Signs = 6,

		[SupportByLibrary("XL12","XL14")]
		xl3Symbols = 7,

		[SupportByLibrary("XL12","XL14")]
		xl3Symbols2 = 8,

		[SupportByLibrary("XL12","XL14")]
		xl4Arrows = 9,

		[SupportByLibrary("XL12","XL14")]
		xl4ArrowsGray = 10,

		[SupportByLibrary("XL12","XL14")]
		xl4RedToBlack = 11,

		[SupportByLibrary("XL12","XL14")]
		xl4CRV = 12,

		[SupportByLibrary("XL12","XL14")]
		xl4TrafficLights = 13,

		[SupportByLibrary("XL12","XL14")]
		xl5Arrows = 14,

		[SupportByLibrary("XL12","XL14")]
		xl5ArrowsGray = 15,

		[SupportByLibrary("XL12","XL14")]
		xl5CRV = 16,

		[SupportByLibrary("XL12","XL14")]
		xl5Quarters = 17,

		[SupportByLibrary("XL14")]
		xlCustomSet = -1,

		[SupportByLibrary("XL14")]
		xl3Stars = 18,

		[SupportByLibrary("XL14")]
		xl3Triangles = 19,

		[SupportByLibrary("XL14")]
		xl5Boxes = 20
	}
}
