//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlLineStyle
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlContinuous = 1,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlDash = -4115,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlDashDot = 4,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlDashDotDot = 5,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlDot = -4118,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlDouble = -4119,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlSlantDashDot = 13,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlLineStyleNone = -4142
	}
}
