//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL11","XL12","XL14")]
	public enum XlListObjectSourceType
	{
		[SupportByLibrary("XL11","XL12","XL14")]
		xlSrcExternal = 0,

		[SupportByLibrary("XL11","XL12","XL14")]
		xlSrcRange = 1,

		[SupportByLibrary("XL11","XL12","XL14")]
		xlSrcXml = 2,

		[SupportByLibrary("XL12","XL14")]
		xlSrcQuery = 3
	}
}
