//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlMouseButton
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlNoButton = 0,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPrimaryButton = 1,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlSecondaryButton = 2
	}
}
