//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlMousePointer
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlIBeam = 3,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlDefault = -4143,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlNorthwestArrow = 1,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlWait = 2
	}
}
