//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlPasteSpecialOperation
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPasteSpecialOperationAdd = 2,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPasteSpecialOperationDivide = 5,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPasteSpecialOperationMultiply = 4,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPasteSpecialOperationNone = -4142,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPasteSpecialOperationSubtract = 3
	}
}
