//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlPivotFieldDataType
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlDate = 2,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlNumber = -4145,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlText = -4158
	}
}
