//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14")]
	public enum XlPivotTableMissingItems
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlMissingItemsDefault = -1,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlMissingItemsNone = 0,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlMissingItemsMax = 32500,

		[SupportByLibrary("XL12","XL14")]
		xlMissingItemsMax2 = 1048576
	}
}
