//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14")]
	public enum XlRangeValueDataType
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlRangeValueDefault = 10,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlRangeValueXMLSpreadsheet = 11,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlRangeValueMSPersistXML = 12
	}
}
