//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlRoutingSlipStatus
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlNotYetRouted = 0,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlRoutingComplete = 2,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlRoutingInProgress = 1
	}
}
