//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlSizeRepresents
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlSizeIsWidth = 2,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlSizeIsArea = 1
	}
}
