//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL14")]
	public enum XlSlicerCrossFilterType
	{
		[SupportByLibrary("XL14")]
		xlSlicerNoCrossFilter = 1,

		[SupportByLibrary("XL14")]
		xlSlicerCrossFilterShowItemsWithDataAtTop = 2,

		[SupportByLibrary("XL14")]
		xlSlicerCrossFilterShowItemsWithNoData = 3
	}
}
