//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlSortOrientation
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlSortRows = 2,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlSortColumns = 1
	}
}
