//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlWBATemplate
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlWBATChart = -4109,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlWBATExcel4IntlMacroSheet = 4,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlWBATExcel4MacroSheet = 3,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlWBATWorksheet = -4167
	}
}
