//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.VBIDE
{
	[SupportByLibrary("VBE")]
	public class _Component : COMObject
	{
		#region Construction

		public _Component(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public _Component(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public _Component(COMObject replacedObject) : base(replacedObject)
		{
		}

		public _Component()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("VBE")]
		public LateBindingApi.VBIDE.Application Application
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Application");
				if(null == returnValue)
					return null;
				LateBindingApi.VBIDE.Application newClass = new LateBindingApi.VBIDE.Application(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("VBE")]
		public LateBindingApi.VBIDE.Components Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				if(null == returnValue)
					return null;
				LateBindingApi.VBIDE.Components newClass = new LateBindingApi.VBIDE.Components(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("VBE")]
		public bool IsDirty
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "IsDirty");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "IsDirty", value);
			}						
		}


		[SupportByLibrary("VBE")]
		public string Name
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Name");
				return (string)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Name", value);
			}						
		}


		#endregion

		#region Methods

		#endregion

	}
}
