//Generated by LateBindingApi.CodeGenerator
using System;
using System.ComponentModel;
using LateBindingApi.Core;
namespace LateBindingApi.VBIDE
{
	[SupportByLibrary("VBE")]
	public class Components : _Components
	{
		#region Construction

		public Components(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public Components(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public Components(COMObject replacedObject) : base(replacedObject)
		{
		}

		public Components()
		{
			CreateFromProgId("VBIDE.Components");
		}

		public Components(string progId)
		{
			CreateFromProgId(progId);
		}

		#endregion


	}
}
