//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlBordersIndex
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlInsideHorizontal = 12,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlInsideVertical = 11,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlDiagonalDown = 5,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlDiagonalUp = 6,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlEdgeBottom = 9,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlEdgeLeft = 7,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlEdgeRight = 10,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlEdgeTop = 8
	}
}
