//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14")]
	public enum XlCalculationInterruptKey
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlNoKey = 0,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlEscKey = 1,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlAnyKey = 2
	}
}
