//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlDataSeriesDate
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlDay = 1,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlMonth = 3,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlWeekday = 2,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlYear = 4
	}
}
