//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14")]
	public enum XlDataLabelSeparator
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlDataLabelSeparatorDefault = 1
	}
}
