//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlDisplayUnit
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlHundreds = -2,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlThousands = -3,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlTenThousands = -4,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlHundredThousands = -5,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlMillions = -6,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlTenMillions = -7,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlHundredMillions = -8,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlThousandMillions = -9,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlMillionMillions = -10
	}
}
