//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14")]
	public enum XlErrorChecks
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlEvaluateToError = 1,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlTextDate = 2,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlNumberAsText = 3,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlInconsistentFormula = 4,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlOmittedCells = 5,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlUnlockedFormulaCells = 6,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlEmptyCellReferences = 7,

		[SupportByLibrary("XL11","XL12","XL14")]
		xlListDataValidation = 8,

		[SupportByLibrary("XL12","XL14")]
		xlInconsistentListFormula = 9
	}
}
