//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14")]
	public enum XlImportDataAs
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlQueryTable = 0,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlPivotTableReport = 1,

		[SupportByLibrary("XL12","XL14")]
		xlTable = 2
	}
}
