//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL12","XL14")]
	public enum XlLayoutRowType
	{
		[SupportByLibrary("XL12","XL14")]
		xlCompactRow = 0,

		[SupportByLibrary("XL12","XL14")]
		xlTabularRow = 1,

		[SupportByLibrary("XL12","XL14")]
		xlOutlineRow = 2
	}
}
