//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlLegendPosition
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlLegendPositionBottom = -4107,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlLegendPositionCorner = 2,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlLegendPositionLeft = -4131,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlLegendPositionRight = -4152,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlLegendPositionTop = -4160,

		[SupportByLibrary("XL12","XL14")]
		xlLegendPositionCustom = -4161
	}
}
