//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlLocationInTable
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlColumnHeader = -4110,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlColumnItem = 5,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlDataHeader = 3,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlDataItem = 7,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPageHeader = 2,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPageItem = 6,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlRowHeader = -4153,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlRowItem = 4,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlTableBody = 8
	}
}
