//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlOLEType
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlOLEControl = 2,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlOLEEmbed = 1,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlOLELink = 0
	}
}
