//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlPaperSize
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaper10x14 = 16,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaper11x17 = 17,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperA3 = 8,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperA4 = 9,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperA4Small = 10,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperA5 = 11,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperB4 = 12,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperB5 = 13,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperCsheet = 24,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperDsheet = 25,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperEnvelope10 = 20,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperEnvelope11 = 21,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperEnvelope12 = 22,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperEnvelope14 = 23,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperEnvelope9 = 19,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperEnvelopeB4 = 33,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperEnvelopeB5 = 34,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperEnvelopeB6 = 35,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperEnvelopeC3 = 29,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperEnvelopeC4 = 30,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperEnvelopeC5 = 28,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperEnvelopeC6 = 31,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperEnvelopeC65 = 32,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperEnvelopeDL = 27,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperEnvelopeItaly = 36,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperEnvelopeMonarch = 37,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperEnvelopePersonal = 38,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperEsheet = 26,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperExecutive = 7,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperFanfoldLegalGerman = 41,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperFanfoldStdGerman = 40,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperFanfoldUS = 39,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperFolio = 14,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperLedger = 4,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperLegal = 5,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperLetter = 1,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperLetterSmall = 2,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperNote = 18,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperQuarto = 15,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperStatement = 6,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperTabloid = 3,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlPaperUser = 256
	}
}
