//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14")]
	public enum XlPivotCellType
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlPivotCellValue = 0,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlPivotCellPivotItem = 1,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlPivotCellSubtotal = 2,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlPivotCellGrandTotal = 3,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlPivotCellDataField = 4,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlPivotCellPivotField = 5,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlPivotCellPageFieldItem = 6,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlPivotCellCustomSubtotal = 7,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlPivotCellDataPivotField = 8,

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		xlPivotCellBlankCell = 9
	}
}
