//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlPlacement
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlFreeFloating = 3,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlMove = 2,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlMoveAndSize = 1
	}
}
