//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL14")]
	public enum XlPortugueseReform
	{
		[SupportByLibrary("XL14")]
		xlPortuguesePreReform = 1,

		[SupportByLibrary("XL14")]
		xlPortuguesePostReform = 2,

		[SupportByLibrary("XL14")]
		xlPortugueseBoth = 3
	}
}
