//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlSpecialCellsValue
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlErrors = 16,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlLogical = 4,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlNumbers = 1,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlTextValues = 2
	}
}
