//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL14")]
	public enum XlSpanishModes
	{
		[SupportByLibrary("XL14")]
		xlSpanishTuteoOnly = 0,

		[SupportByLibrary("XL14")]
		xlSpanishTuteoAndVoseo = 1,

		[SupportByLibrary("XL14")]
		xlSpanishVoseoOnly = 2
	}
}
