//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL14")]
	public enum XlSparklineRowCol
	{
		[SupportByLibrary("XL14")]
		xlSparklineNonSquare = 0,

		[SupportByLibrary("XL14")]
		xlSparklineRowsSquare = 1,

		[SupportByLibrary("XL14")]
		xlSparklineColumnsSquare = 2
	}
}
