//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlSummaryRow
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlSummaryAbove = 0,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlSummaryBelow = 1
	}
}
