//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL12","XL14")]
	public enum XlTableStyleElementType
	{
		[SupportByLibrary("XL12","XL14")]
		xlWholeTable = 0,

		[SupportByLibrary("XL12","XL14")]
		xlHeaderRow = 1,

		[SupportByLibrary("XL12","XL14")]
		xlTotalRow = 2,

		[SupportByLibrary("XL12","XL14")]
		xlGrandTotalRow = 2,

		[SupportByLibrary("XL12","XL14")]
		xlFirstColumn = 3,

		[SupportByLibrary("XL12","XL14")]
		xlLastColumn = 4,

		[SupportByLibrary("XL12","XL14")]
		xlGrandTotalColumn = 4,

		[SupportByLibrary("XL12","XL14")]
		xlRowStripe1 = 5,

		[SupportByLibrary("XL12","XL14")]
		xlRowStripe2 = 6,

		[SupportByLibrary("XL12","XL14")]
		xlColumnStripe1 = 7,

		[SupportByLibrary("XL12","XL14")]
		xlColumnStripe2 = 8,

		[SupportByLibrary("XL12","XL14")]
		xlFirstHeaderCell = 9,

		[SupportByLibrary("XL12","XL14")]
		xlLastHeaderCell = 10,

		[SupportByLibrary("XL12","XL14")]
		xlFirstTotalCell = 11,

		[SupportByLibrary("XL12","XL14")]
		xlLastTotalCell = 12,

		[SupportByLibrary("XL12","XL14")]
		xlSubtotalColumn1 = 13,

		[SupportByLibrary("XL12","XL14")]
		xlSubtotalColumn2 = 14,

		[SupportByLibrary("XL12","XL14")]
		xlSubtotalColumn3 = 15,

		[SupportByLibrary("XL12","XL14")]
		xlSubtotalRow1 = 16,

		[SupportByLibrary("XL12","XL14")]
		xlSubtotalRow2 = 17,

		[SupportByLibrary("XL12","XL14")]
		xlSubtotalRow3 = 18,

		[SupportByLibrary("XL12","XL14")]
		xlBlankRow = 19,

		[SupportByLibrary("XL12","XL14")]
		xlColumnSubheading1 = 20,

		[SupportByLibrary("XL12","XL14")]
		xlColumnSubheading2 = 21,

		[SupportByLibrary("XL12","XL14")]
		xlColumnSubheading3 = 22,

		[SupportByLibrary("XL12","XL14")]
		xlRowSubheading1 = 23,

		[SupportByLibrary("XL12","XL14")]
		xlRowSubheading2 = 24,

		[SupportByLibrary("XL12","XL14")]
		xlRowSubheading3 = 25,

		[SupportByLibrary("XL12","XL14")]
		xlPageFieldLabels = 26,

		[SupportByLibrary("XL12","XL14")]
		xlPageFieldValues = 27,

		[SupportByLibrary("XL14")]
		xlSlicerUnselectedItemWithData = 28,

		[SupportByLibrary("XL14")]
		xlSlicerUnselectedItemWithNoData = 29,

		[SupportByLibrary("XL14")]
		xlSlicerSelectedItemWithData = 30,

		[SupportByLibrary("XL14")]
		xlSlicerSelectedItemWithNoData = 31,

		[SupportByLibrary("XL14")]
		xlSlicerHoveredUnselectedItemWithData = 32,

		[SupportByLibrary("XL14")]
		xlSlicerHoveredSelectedItemWithData = 33,

		[SupportByLibrary("XL14")]
		xlSlicerHoveredUnselectedItemWithNoData = 34,

		[SupportByLibrary("XL14")]
		xlSlicerHoveredSelectedItemWithNoData = 35
	}
}
