//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlTextParsingType
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlDelimited = 1,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlFixedWidth = 2
	}
}
