//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Excel.Enums
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public enum XlWindowState
	{
		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlMaximized = -4137,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlMinimized = -4140,

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		xlNormal = -4143
	}
}
