//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
using System.Collections;
namespace LateBindingApi.Excel
{
	[SupportByLibrary("XL10","XL11","XL12","XL14")]
	public class CalculatedMembers : COMObject
	{
		#region Construction

		public CalculatedMembers(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public CalculatedMembers(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public CalculatedMembers(COMObject replacedObject) : base(replacedObject)
		{
		}

		public CalculatedMembers()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public LateBindingApi.Excel.Application Application
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Application");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.Application newClass = new LateBindingApi.Excel.Application(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public LateBindingApi.Excel.Enums.XlCreator Creator
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Creator");
				return (LateBindingApi.Excel.Enums.XlCreator)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public Int32 Count
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Count");
				return (Int32)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public LateBindingApi.Excel.CalculatedMember this[object index]
		{
			get
			{
				object[] paramArray = new object[1];
				paramArray[0] = index;		
				object returnValue = Invoker.PropertyGet(this, "Item", paramArray);
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.CalculatedMember newClass = new LateBindingApi.Excel.CalculatedMember(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public LateBindingApi.Excel.CalculatedMember get__Default(object index)
		{
			object[] paramArray = new object[1];
			paramArray[0] = index;
			object returnValue = Invoker.PropertyGet(this, "_Default", paramArray);
			if(null == returnValue)
				return null;
			LateBindingApi.Excel.CalculatedMember newClass = new LateBindingApi.Excel.CalculatedMember(this, returnValue);
			return newClass;
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public IEnumerator GetEnumerator()
		{
			object enumProxy = Invoker.PropertyGet(this, "_NewEnum");
			COMObject enumerator = new COMObject(this, enumProxy);
			Invoker.Method(enumerator, "Reset", null);
			bool isMoveNextTrue = (bool)Invoker.MethodReturn(enumerator, "MoveNext", null);
            while (true == isMoveNextTrue)
            {
                object itemProxy = Invoker.PropertyGet(enumerator, "Current", null);
				LateBindingApi.Excel.CalculatedMember returnClass = new LateBindingApi.Excel.CalculatedMember (this, itemProxy);
				isMoveNextTrue = (bool)Invoker.MethodReturn(enumerator, "MoveNext", null);
				yield return returnClass;
            }
		}

		#endregion

		#region Methods

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public LateBindingApi.Excel.CalculatedMember Add(string name, string formula)
		{
			object[] paramArray = new object[2];
			paramArray[0] = name;
			paramArray[1] = formula;
			object returnValue = Invoker.MethodReturn(this, "Add", paramArray);
			if(null == returnValue)
				return null;
			LateBindingApi.Excel.CalculatedMember newClass = new LateBindingApi.Excel.CalculatedMember(this, returnValue);
			return newClass;
		}

		[SupportByLibrary("XL10","XL11","XL12")]
		public LateBindingApi.Excel.CalculatedMember Add(string name, string formula, object solveOrder, object type)
		{
			object[] paramArray = new object[4];
			paramArray[0] = name;
			paramArray[1] = formula;
			paramArray[2] = solveOrder;
			paramArray[3] = type;
			object returnValue = Invoker.MethodReturn(this, "Add", paramArray);
			if(null == returnValue)
				return null;
			LateBindingApi.Excel.CalculatedMember newClass = new LateBindingApi.Excel.CalculatedMember(this, returnValue);
			return newClass;
		}

		[SupportByLibrary("XL14")]
		public LateBindingApi.Excel.CalculatedMember Add(string name, object formula, object solveOrder, object type, object dynamic, object displayFolder, object hierarchizeDistinct)
		{
			object[] paramArray = new object[7];
			paramArray[0] = name;
			paramArray[1] = formula;
			paramArray[2] = solveOrder;
			paramArray[3] = type;
			paramArray[4] = dynamic;
			paramArray[5] = displayFolder;
			paramArray[6] = hierarchizeDistinct;
			object returnValue = Invoker.MethodReturn(this, "Add", paramArray);
			if(null == returnValue)
				return null;
			LateBindingApi.Excel.CalculatedMember newClass = new LateBindingApi.Excel.CalculatedMember(this, returnValue);
			return newClass;
		}

		[SupportByLibrary("XL14")]
		public LateBindingApi.Excel.CalculatedMember _Add(string name, string formula)
		{
			object[] paramArray = new object[2];
			paramArray[0] = name;
			paramArray[1] = formula;
			object returnValue = Invoker.MethodReturn(this, "_Add", paramArray);
			if(null == returnValue)
				return null;
			LateBindingApi.Excel.CalculatedMember newClass = new LateBindingApi.Excel.CalculatedMember(this, returnValue);
			return newClass;
		}

		[SupportByLibrary("XL14")]
		public LateBindingApi.Excel.CalculatedMember _Add(string name, string formula, object solveOrder, object type)
		{
			object[] paramArray = new object[4];
			paramArray[0] = name;
			paramArray[1] = formula;
			paramArray[2] = solveOrder;
			paramArray[3] = type;
			object returnValue = Invoker.MethodReturn(this, "_Add", paramArray);
			if(null == returnValue)
				return null;
			LateBindingApi.Excel.CalculatedMember newClass = new LateBindingApi.Excel.CalculatedMember(this, returnValue);
			return newClass;
		}

		#endregion

	}
}
