//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
using System.Collections;
namespace LateBindingApi.Excel
{
	[SupportByLibrary("XL10","XL11","XL12","XL14")]
	public class DiagramNodeChildren : LateBindingApi.Office._IMsoDispObj
	{
		#region Construction

		public DiagramNodeChildren(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public DiagramNodeChildren(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public DiagramNodeChildren(COMObject replacedObject) : base(replacedObject)
		{
		}

		public DiagramNodeChildren()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public IEnumerator GetEnumerator()
		{
			object enumProxy = Invoker.PropertyGet(this, "_NewEnum");
			COMObject enumerator = new COMObject(this, enumProxy);
			Invoker.Method(enumerator, "Reset", null);
			bool isMoveNextTrue = (bool)Invoker.MethodReturn(enumerator, "MoveNext", null);
            while (true == isMoveNextTrue)
            {
                object itemProxy = Invoker.PropertyGet(enumerator, "Current", null);
				LateBindingApi.Excel.DiagramNode returnClass = new LateBindingApi.Excel.DiagramNode (this, itemProxy);
				isMoveNextTrue = (bool)Invoker.MethodReturn(enumerator, "MoveNext", null);
				yield return returnClass;
            }
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public Int32 Count
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Count");
				return (Int32)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public LateBindingApi.Excel.DiagramNode FirstChild
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "FirstChild");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.DiagramNode newClass = new LateBindingApi.Excel.DiagramNode(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public LateBindingApi.Excel.DiagramNode LastChild
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "LastChild");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.DiagramNode newClass = new LateBindingApi.Excel.DiagramNode(this, returnValue);
				return newClass;
			}
		}

		#endregion

		#region Methods

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public LateBindingApi.Excel.DiagramNode this[object index]
		{
			get
			{
				object[] paramArray = new object[1];
				paramArray[0] = index;		
				object returnValue = Invoker.MethodReturn(this, "Item", paramArray);
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.DiagramNode newClass = new LateBindingApi.Excel.DiagramNode(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public LateBindingApi.Excel.DiagramNode AddNode(object index, LateBindingApi.Office.Enums.MsoDiagramNodeType nodeType)
		{
			object[] paramArray = new object[2];
			paramArray[0] = index;
			paramArray[1] = nodeType;
			object returnValue = Invoker.MethodReturn(this, "AddNode", paramArray);
			if(null == returnValue)
				return null;
			LateBindingApi.Excel.DiagramNode newClass = new LateBindingApi.Excel.DiagramNode(this, returnValue);
			return newClass;
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public void SelectAll()
		{
			Invoker.Method(this, "SelectAll", null);
		}

		#endregion

	}
}
