//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Excel
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public class Interior : COMObject
	{
		#region Construction

		public Interior(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public Interior(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public Interior(COMObject replacedObject) : base(replacedObject)
		{
		}

		public Interior()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Application Application
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Application");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.Application newClass = new LateBindingApi.Excel.Application(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Enums.XlCreator Creator
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Creator");
				return (LateBindingApi.Excel.Enums.XlCreator)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Double Color
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Color");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Color", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMVariant ColorIndex
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "ColorIndex");
				COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
				return returnObject;
			}
			set
			{
				Invoker.PropertySet(this, "ColorIndex", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMVariant InvertIfNegative
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "InvertIfNegative");
				COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
				return returnObject;
			}
			set
			{
				Invoker.PropertySet(this, "InvertIfNegative", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMVariant Pattern
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Pattern");
				COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
				return returnObject;
			}
			set
			{
				Invoker.PropertySet(this, "Pattern", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMVariant PatternColor
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "PatternColor");
				COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
				return returnObject;
			}
			set
			{
				Invoker.PropertySet(this, "PatternColor", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMVariant PatternColorIndex
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "PatternColorIndex");
				COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
				return returnObject;
			}
			set
			{
				Invoker.PropertySet(this, "PatternColorIndex", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public COMVariant ThemeColor
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "ThemeColor");
				COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
				return returnObject;
			}
			set
			{
				Invoker.PropertySet(this, "ThemeColor", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public COMVariant TintAndShade
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "TintAndShade");
				COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
				return returnObject;
			}
			set
			{
				Invoker.PropertySet(this, "TintAndShade", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public COMVariant PatternThemeColor
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "PatternThemeColor");
				COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
				return returnObject;
			}
			set
			{
				Invoker.PropertySet(this, "PatternThemeColor", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public COMVariant PatternTintAndShade
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "PatternTintAndShade");
				COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
				return returnObject;
			}
			set
			{
				Invoker.PropertySet(this, "PatternTintAndShade", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public COMObject Gradient
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Gradient");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		#endregion

		#region Methods

		#endregion

	}
}
