//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Excel
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public class LegendKey : COMObject
	{
		#region Construction

		public LegendKey(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public LegendKey(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public LegendKey(COMObject replacedObject) : base(replacedObject)
		{
		}

		public LegendKey()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Application Application
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Application");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.Application newClass = new LateBindingApi.Excel.Application(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Enums.XlCreator Creator
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Creator");
				return (LateBindingApi.Excel.Enums.XlCreator)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Border Border
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Border");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.Border newClass = new LateBindingApi.Excel.Border(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Interior Interior
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Interior");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.Interior newClass = new LateBindingApi.Excel.Interior(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.ChartFillFormat Fill
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Fill");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.ChartFillFormat newClass = new LateBindingApi.Excel.ChartFillFormat(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public bool InvertIfNegative
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "InvertIfNegative");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "InvertIfNegative", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Int32 MarkerBackgroundColor
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MarkerBackgroundColor");
				return (Int32)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MarkerBackgroundColor", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Enums.XlColorIndex MarkerBackgroundColorIndex
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MarkerBackgroundColorIndex");
				return (LateBindingApi.Excel.Enums.XlColorIndex)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MarkerBackgroundColorIndex", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Int32 MarkerForegroundColor
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MarkerForegroundColor");
				return (Int32)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MarkerForegroundColor", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Enums.XlColorIndex MarkerForegroundColorIndex
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MarkerForegroundColorIndex");
				return (LateBindingApi.Excel.Enums.XlColorIndex)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MarkerForegroundColorIndex", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Int32 MarkerSize
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MarkerSize");
				return (Int32)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MarkerSize", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Enums.XlMarkerStyle MarkerStyle
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MarkerStyle");
				return (LateBindingApi.Excel.Enums.XlMarkerStyle)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MarkerStyle", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Int32 PictureType
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "PictureType");
				return (Int32)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "PictureType", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Int32 PictureUnit
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "PictureUnit");
				return (Int32)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "PictureUnit", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public bool Smooth
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Smooth");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Smooth", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Double Left
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Left");
				return (Double)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Double Top
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Top");
				return (Double)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Double Width
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Width");
				return (Double)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Double Height
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Height");
				return (Double)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public bool Shadow
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Shadow");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Shadow", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public Double PictureUnit2
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "PictureUnit2");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "PictureUnit2", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Excel.ChartFormat Format
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Format");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.ChartFormat newClass = new LateBindingApi.Excel.ChartFormat(this, returnValue);
				return newClass;
			}
		}

		#endregion

		#region Methods

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMVariant ClearFormats()
		{
			object returnValue = Invoker.MethodReturn(this, "ClearFormats", null);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMVariant Delete()
		{
			object returnValue = Invoker.MethodReturn(this, "Delete", null);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMVariant Select()
		{
			object returnValue = Invoker.MethodReturn(this, "Select", null);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		#endregion

	}
}
