//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Excel
{
	[SupportByLibrary("XL14")]
	public class NegativeBarFormat : COMObject
	{
		#region Construction

		public NegativeBarFormat(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public NegativeBarFormat(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public NegativeBarFormat(COMObject replacedObject) : base(replacedObject)
		{
		}

		public NegativeBarFormat()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("XL14")]
		public LateBindingApi.Excel.Application Application
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Application");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.Application newClass = new LateBindingApi.Excel.Application(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL14")]
		public LateBindingApi.Excel.Enums.XlCreator Creator
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Creator");
				return (LateBindingApi.Excel.Enums.XlCreator)returnValue;
			}
		}

		[SupportByLibrary("XL14")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL14")]
		public LateBindingApi.Excel.Enums.XlDataBarNegativeColorType ColorType
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "ColorType");
				return (LateBindingApi.Excel.Enums.XlDataBarNegativeColorType)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "ColorType", value);
			}						
		}


		[SupportByLibrary("XL14")]
		public LateBindingApi.Excel.Enums.XlDataBarNegativeColorType BorderColorType
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "BorderColorType");
				return (LateBindingApi.Excel.Enums.XlDataBarNegativeColorType)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "BorderColorType", value);
			}						
		}


		[SupportByLibrary("XL14")]
		public COMObject Color
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Color");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL14")]
		public COMObject BorderColor
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "BorderColor");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		#endregion

		#region Methods

		#endregion

	}
}
