//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Excel
{
	[SupportByLibrary("XL12","XL14")]
	public class RectangularGradient : COMObject
	{
		#region Construction

		public RectangularGradient(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public RectangularGradient(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public RectangularGradient(COMObject replacedObject) : base(replacedObject)
		{
		}

		public RectangularGradient()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Excel.Application Application
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Application");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.Application newClass = new LateBindingApi.Excel.Application(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Excel.Enums.XlCreator Creator
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Creator");
				return (LateBindingApi.Excel.Enums.XlCreator)returnValue;
			}
		}

		[SupportByLibrary("XL12","XL14")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Excel.ColorStops ColorStops
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "ColorStops");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.ColorStops newClass = new LateBindingApi.Excel.ColorStops(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL12","XL14")]
		public Double RectangleTop
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "RectangleTop");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "RectangleTop", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public Double RectangleBottom
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "RectangleBottom");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "RectangleBottom", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public Double RectangleLeft
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "RectangleLeft");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "RectangleLeft", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public Double RectangleRight
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "RectangleRight");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "RectangleRight", value);
			}						
		}


		#endregion

		#region Methods

		#endregion

	}
}
