//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Excel
{
	[SupportByLibrary("XL10","XL11","XL12","XL14")]
	public class SmartTagOptions : COMObject
	{
		#region Construction

		public SmartTagOptions(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public SmartTagOptions(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public SmartTagOptions(COMObject replacedObject) : base(replacedObject)
		{
		}

		public SmartTagOptions()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public LateBindingApi.Excel.Application Application
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Application");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.Application newClass = new LateBindingApi.Excel.Application(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public LateBindingApi.Excel.Enums.XlCreator Creator
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Creator");
				return (LateBindingApi.Excel.Enums.XlCreator)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public LateBindingApi.Excel.Enums.XlSmartTagDisplayMode DisplaySmartTags
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "DisplaySmartTags");
				return (LateBindingApi.Excel.Enums.XlSmartTagDisplayMode)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "DisplaySmartTags", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public bool EmbedSmartTags
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "EmbedSmartTags");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "EmbedSmartTags", value);
			}						
		}


		#endregion

		#region Methods

		#endregion

	}
}
