//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Excel
{
	[SupportByLibrary("XL12","XL14")]
	public class Sort : COMObject
	{
		#region Construction

		public Sort(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public Sort(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public Sort(COMObject replacedObject) : base(replacedObject)
		{
		}

		public Sort()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Excel.Application Application
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Application");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.Application newClass = new LateBindingApi.Excel.Application(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Excel.Enums.XlCreator Creator
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Creator");
				return (LateBindingApi.Excel.Enums.XlCreator)returnValue;
			}
		}

		[SupportByLibrary("XL12","XL14")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Excel.Range Rng
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Rng");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.Range newClass = new LateBindingApi.Excel.Range(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Excel.Enums.XlYesNoGuess Header
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Header");
				return (LateBindingApi.Excel.Enums.XlYesNoGuess)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Header", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public bool MatchCase
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MatchCase");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MatchCase", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Excel.Enums.XlSortOrientation Orientation
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Orientation");
				return (LateBindingApi.Excel.Enums.XlSortOrientation)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Orientation", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Excel.Enums.XlSortMethod SortMethod
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "SortMethod");
				return (LateBindingApi.Excel.Enums.XlSortMethod)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "SortMethod", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Excel.SortFields SortFields
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "SortFields");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.SortFields newClass = new LateBindingApi.Excel.SortFields(this, returnValue);
				return newClass;
			}
		}

		#endregion

		#region Methods

		[SupportByLibrary("XL12","XL14")]
		public void SetRange(LateBindingApi.Excel.Range rng)
		{
			object[] paramArray = new object[1];
			paramArray.SetValue(rng,0);
			Invoker.Method(this, "SetRange", paramArray);
		}

		[SupportByLibrary("XL12","XL14")]
		public void Apply()
		{
			Invoker.Method(this, "Apply", null);
		}

		#endregion

	}
}
