//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Excel
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public class ThreeDFormat : LateBindingApi.Office._IMsoDispObj
	{
		#region Construction

		public ThreeDFormat(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public ThreeDFormat(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public ThreeDFormat(COMObject replacedObject) : base(replacedObject)
		{
		}

		public ThreeDFormat()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Double Depth
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Depth");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Depth", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.ColorFormat ExtrusionColor
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "ExtrusionColor");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.ColorFormat newClass = new LateBindingApi.Excel.ColorFormat(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Office.Enums.MsoExtrusionColorType ExtrusionColorType
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "ExtrusionColorType");
				return (LateBindingApi.Office.Enums.MsoExtrusionColorType)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "ExtrusionColorType", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Office.Enums.MsoTriState Perspective
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Perspective");
				return (LateBindingApi.Office.Enums.MsoTriState)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Perspective", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Office.Enums.MsoPresetExtrusionDirection PresetExtrusionDirection
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "PresetExtrusionDirection");
				return (LateBindingApi.Office.Enums.MsoPresetExtrusionDirection)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Office.Enums.MsoPresetLightingDirection PresetLightingDirection
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "PresetLightingDirection");
				return (LateBindingApi.Office.Enums.MsoPresetLightingDirection)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "PresetLightingDirection", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Office.Enums.MsoPresetLightingSoftness PresetLightingSoftness
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "PresetLightingSoftness");
				return (LateBindingApi.Office.Enums.MsoPresetLightingSoftness)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "PresetLightingSoftness", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Office.Enums.MsoPresetMaterial PresetMaterial
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "PresetMaterial");
				return (LateBindingApi.Office.Enums.MsoPresetMaterial)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "PresetMaterial", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Office.Enums.MsoPresetThreeDFormat PresetThreeDFormat
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "PresetThreeDFormat");
				return (LateBindingApi.Office.Enums.MsoPresetThreeDFormat)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Double RotationX
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "RotationX");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "RotationX", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Double RotationY
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "RotationY");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "RotationY", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Office.Enums.MsoTriState Visible
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Visible");
				return (LateBindingApi.Office.Enums.MsoTriState)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Visible", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Office.Enums.MsoLightRigType PresetLighting
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "PresetLighting");
				return (LateBindingApi.Office.Enums.MsoLightRigType)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "PresetLighting", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public Double Z
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Z");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Z", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Office.Enums.MsoBevelType BevelTopType
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "BevelTopType");
				return (LateBindingApi.Office.Enums.MsoBevelType)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "BevelTopType", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public Double BevelTopInset
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "BevelTopInset");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "BevelTopInset", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public Double BevelTopDepth
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "BevelTopDepth");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "BevelTopDepth", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Office.Enums.MsoBevelType BevelBottomType
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "BevelBottomType");
				return (LateBindingApi.Office.Enums.MsoBevelType)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "BevelBottomType", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public Double BevelBottomInset
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "BevelBottomInset");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "BevelBottomInset", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public Double BevelBottomDepth
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "BevelBottomDepth");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "BevelBottomDepth", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Office.Enums.MsoPresetCamera PresetCamera
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "PresetCamera");
				return (LateBindingApi.Office.Enums.MsoPresetCamera)returnValue;
			}
		}

		[SupportByLibrary("XL12","XL14")]
		public Double RotationZ
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "RotationZ");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "RotationZ", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public Double ContourWidth
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "ContourWidth");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "ContourWidth", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Excel.ColorFormat ContourColor
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "ContourColor");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.ColorFormat newClass = new LateBindingApi.Excel.ColorFormat(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL12","XL14")]
		public Double FieldOfView
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "FieldOfView");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "FieldOfView", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Office.Enums.MsoTriState ProjectText
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "ProjectText");
				return (LateBindingApi.Office.Enums.MsoTriState)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "ProjectText", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public Double LightAngle
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "LightAngle");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "LightAngle", value);
			}						
		}


		#endregion

		#region Methods

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public void IncrementRotationX(Double increment)
		{
			object[] paramArray = new object[1];
			paramArray[0] = increment;
			Invoker.Method(this, "IncrementRotationX", paramArray);
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public void IncrementRotationY(Double increment)
		{
			object[] paramArray = new object[1];
			paramArray[0] = increment;
			Invoker.Method(this, "IncrementRotationY", paramArray);
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public void ResetRotation()
		{
			Invoker.Method(this, "ResetRotation", null);
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public void SetThreeDFormat(LateBindingApi.Office.Enums.MsoPresetThreeDFormat presetThreeDFormat)
		{
			object[] paramArray = new object[1];
			paramArray[0] = presetThreeDFormat;
			Invoker.Method(this, "SetThreeDFormat", paramArray);
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public void SetExtrusionDirection(LateBindingApi.Office.Enums.MsoPresetExtrusionDirection presetExtrusionDirection)
		{
			object[] paramArray = new object[1];
			paramArray[0] = presetExtrusionDirection;
			Invoker.Method(this, "SetExtrusionDirection", paramArray);
		}

		[SupportByLibrary("XL12","XL14")]
		public void SetPresetCamera(LateBindingApi.Office.Enums.MsoPresetCamera presetCamera)
		{
			object[] paramArray = new object[1];
			paramArray[0] = presetCamera;
			Invoker.Method(this, "SetPresetCamera", paramArray);
		}

		[SupportByLibrary("XL12","XL14")]
		public void IncrementRotationZ(Double increment)
		{
			object[] paramArray = new object[1];
			paramArray[0] = increment;
			Invoker.Method(this, "IncrementRotationZ", paramArray);
		}

		[SupportByLibrary("XL12","XL14")]
		public void IncrementRotationHorizontal(Double increment)
		{
			object[] paramArray = new object[1];
			paramArray[0] = increment;
			Invoker.Method(this, "IncrementRotationHorizontal", paramArray);
		}

		[SupportByLibrary("XL12","XL14")]
		public void IncrementRotationVertical(Double increment)
		{
			object[] paramArray = new object[1];
			paramArray[0] = increment;
			Invoker.Method(this, "IncrementRotationVertical", paramArray);
		}

		#endregion

	}
}
