//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Excel
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public class WebOptions : COMObject
	{
		#region Construction

		public WebOptions(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public WebOptions(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public WebOptions(COMObject replacedObject) : base(replacedObject)
		{
		}

		public WebOptions()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Application Application
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Application");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.Application newClass = new LateBindingApi.Excel.Application(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Enums.XlCreator Creator
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Creator");
				return (LateBindingApi.Excel.Enums.XlCreator)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public bool RelyOnCSS
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "RelyOnCSS");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "RelyOnCSS", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public bool OrganizeInFolder
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "OrganizeInFolder");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "OrganizeInFolder", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public bool UseLongFileNames
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "UseLongFileNames");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "UseLongFileNames", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public bool DownloadComponents
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "DownloadComponents");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "DownloadComponents", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public bool RelyOnVML
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "RelyOnVML");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "RelyOnVML", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public bool AllowPNG
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "AllowPNG");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "AllowPNG", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Office.Enums.MsoScreenSize ScreenSize
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "ScreenSize");
				return (LateBindingApi.Office.Enums.MsoScreenSize)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "ScreenSize", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Int32 PixelsPerInch
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "PixelsPerInch");
				return (Int32)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "PixelsPerInch", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public string LocationOfComponents
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "LocationOfComponents");
				return (string)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "LocationOfComponents", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Office.Enums.MsoEncoding Encoding
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Encoding");
				return (LateBindingApi.Office.Enums.MsoEncoding)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Encoding", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public string FolderSuffix
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "FolderSuffix");
				return (string)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public LateBindingApi.Office.Enums.MsoTargetBrowser TargetBrowser
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "TargetBrowser");
				return (LateBindingApi.Office.Enums.MsoTargetBrowser)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "TargetBrowser", value);
			}						
		}


		#endregion

		#region Methods

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public void UseDefaultFolderSuffix()
		{
			Invoker.Method(this, "UseDefaultFolderSuffix", null);
		}

		#endregion

	}
}
