//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Excel
{
	[SupportByLibrary("XL12","XL14")]
	public class WorksheetView : COMObject
	{
		#region Construction

		public WorksheetView(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public WorksheetView(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public WorksheetView(COMObject replacedObject) : base(replacedObject)
		{
		}

		public WorksheetView()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Excel.Application Application
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Application");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.Application newClass = new LateBindingApi.Excel.Application(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Excel.Enums.XlCreator Creator
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Creator");
				return (LateBindingApi.Excel.Enums.XlCreator)returnValue;
			}
		}

		[SupportByLibrary("XL12","XL14")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL12","XL14")]
		public COMObject Sheet
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Sheet");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL12","XL14")]
		public bool DisplayGridlines
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "DisplayGridlines");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "DisplayGridlines", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public bool DisplayFormulas
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "DisplayFormulas");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "DisplayFormulas", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public bool DisplayHeadings
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "DisplayHeadings");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "DisplayHeadings", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public bool DisplayOutline
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "DisplayOutline");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "DisplayOutline", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public bool DisplayZeros
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "DisplayZeros");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "DisplayZeros", value);
			}						
		}


		#endregion

		#region Methods

		#endregion

	}
}
