//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.VBIDE.Enums
{
	[SupportByLibrary("VBE")]
	public enum Vbext_ProjectProtection
	{
		[SupportByLibrary("VBE")]
		vbext_pp_none = 0,

		[SupportByLibrary("VBE")]
		vbext_pp_locked = 1
	}
}
