//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public enum MsoAnimationType
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationIdle = 1,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationGreeting = 2,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationGoodbye = 3,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationBeginSpeaking = 4,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationRestPose = 5,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationCharacterSuccessMajor = 6,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationGetAttentionMajor = 11,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationGetAttentionMinor = 12,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationSearching = 13,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationPrinting = 18,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationGestureRight = 19,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationWritingNotingSomething = 22,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationWorkingAtSomething = 23,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationThinking = 24,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationSendingMail = 25,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationListensToComputer = 26,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationDisappear = 31,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationAppear = 32,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationGetArtsy = 100,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationGetTechy = 101,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationGetWizardy = 102,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationCheckingSomething = 103,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationLookDown = 104,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationLookDownLeft = 105,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationLookDownRight = 106,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationLookLeft = 107,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationLookRight = 108,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationLookUp = 109,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationLookUpLeft = 110,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationLookUpRight = 111,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationSaving = 112,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationGestureDown = 113,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationGestureLeft = 114,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationGestureUp = 115,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAnimationEmptyTrash = 116
	}
}
