//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public enum MsoBarProtection
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoBarNoProtection = 0,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoBarNoCustomize = 1,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoBarNoResize = 2,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoBarNoMove = 4,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoBarNoChangeVisible = 8,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoBarNoChangeDock = 16,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoBarNoVerticalDock = 32,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoBarNoHorizontalDock = 64
	}
}
