//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum MsoBevelType
	{
		[SupportByLibrary("OF12","OF14")]
		msoBevelTypeMixed = -2,

		[SupportByLibrary("OF12","OF14")]
		msoBevelNone = 1,

		[SupportByLibrary("OF12","OF14")]
		msoBevelRelaxedInset = 2,

		[SupportByLibrary("OF12","OF14")]
		msoBevelCircle = 3,

		[SupportByLibrary("OF12","OF14")]
		msoBevelSlope = 4,

		[SupportByLibrary("OF12","OF14")]
		msoBevelCross = 5,

		[SupportByLibrary("OF12","OF14")]
		msoBevelAngle = 6,

		[SupportByLibrary("OF12","OF14")]
		msoBevelSoftRound = 7,

		[SupportByLibrary("OF12","OF14")]
		msoBevelConvex = 8,

		[SupportByLibrary("OF12","OF14")]
		msoBevelCoolSlant = 9,

		[SupportByLibrary("OF12","OF14")]
		msoBevelDivot = 10,

		[SupportByLibrary("OF12","OF14")]
		msoBevelRiblet = 11,

		[SupportByLibrary("OF12","OF14")]
		msoBevelHardEdge = 12,

		[SupportByLibrary("OF12","OF14")]
		msoBevelArtDeco = 13
	}
}
