//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF14")]
	public enum MsoContactCardStyle
	{
		[SupportByLibrary("OF14")]
		msoContactCardHover = 0,

		[SupportByLibrary("OF14")]
		msoContactCardFull = 1
	}
}
