//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public enum MsoExtraInfoMethod
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoMethodGet = 0,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoMethodPost = 1
	}
}
