//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF14")]
	public enum MsoFileValidationMode
	{
		[SupportByLibrary("OF14")]
		msoFileValidationDefault = 0,

		[SupportByLibrary("OF14")]
		msoFileValidationSkip = 1
	}
}
