//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public enum MsoGradientStyle
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoGradientMixed = -2,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoGradientHorizontal = 1,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoGradientVertical = 2,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoGradientDiagonalUp = 3,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoGradientDiagonalDown = 4,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoGradientFromCorner = 5,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoGradientFromTitle = 6,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoGradientFromCenter = 7
	}
}
