//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14")]
	public enum MsoLanguageIDHidden
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoLanguageIDChineseHongKong = 3076,

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoLanguageIDChineseMacao = 5124,

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoLanguageIDEnglishTrinidad = 11273
	}
}
