//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14")]
	public enum MsoMoveRow
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoMoveRowFirst = -4,

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoMoveRowPrev = -3,

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoMoveRowNext = -2,

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoMoveRowNbr = -1
	}
}
