//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public enum MsoMixedType
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoIntegerMixed = 32768,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoSingleMixed = -2147483648
	}
}
