//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public enum MsoPresetMaterial
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoPresetMaterialMixed = -2,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoMaterialMatte = 1,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoMaterialPlastic = 2,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoMaterialMetal = 3,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoMaterialWireFrame = 4,

		[SupportByLibrary("OF12","OF14")]
		msoMaterialMatte2 = 5,

		[SupportByLibrary("OF12","OF14")]
		msoMaterialPlastic2 = 6,

		[SupportByLibrary("OF12","OF14")]
		msoMaterialMetal2 = 7,

		[SupportByLibrary("OF12","OF14")]
		msoMaterialWarmMatte = 8,

		[SupportByLibrary("OF12","OF14")]
		msoMaterialTranslucentPowder = 9,

		[SupportByLibrary("OF12","OF14")]
		msoMaterialPowder = 10,

		[SupportByLibrary("OF12","OF14")]
		msoMaterialDarkEdge = 11,

		[SupportByLibrary("OF12","OF14")]
		msoMaterialSoftEdge = 12,

		[SupportByLibrary("OF12","OF14")]
		msoMaterialClear = 13,

		[SupportByLibrary("OF12","OF14")]
		msoMaterialFlat = 14,

		[SupportByLibrary("OF12","OF14")]
		msoMaterialSoftMetal = 15
	}
}
