//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum MsoPathFormat
	{
		[SupportByLibrary("OF12","OF14")]
		msoPathTypeMixed = -2,

		[SupportByLibrary("OF12","OF14")]
		msoPathTypeNone = 0,

		[SupportByLibrary("OF12","OF14")]
		msoPathType1 = 1,

		[SupportByLibrary("OF12","OF14")]
		msoPathType2 = 2,

		[SupportByLibrary("OF12","OF14")]
		msoPathType3 = 3,

		[SupportByLibrary("OF12","OF14")]
		msoPathType4 = 4
	}
}
