//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum MsoReflectionType
	{
		[SupportByLibrary("OF12","OF14")]
		msoReflectionTypeMixed = -2,

		[SupportByLibrary("OF12","OF14")]
		msoReflectionTypeNone = 0,

		[SupportByLibrary("OF12","OF14")]
		msoReflectionType1 = 1,

		[SupportByLibrary("OF12","OF14")]
		msoReflectionType2 = 2,

		[SupportByLibrary("OF12","OF14")]
		msoReflectionType3 = 3,

		[SupportByLibrary("OF12","OF14")]
		msoReflectionType4 = 4,

		[SupportByLibrary("OF12","OF14")]
		msoReflectionType5 = 5,

		[SupportByLibrary("OF12","OF14")]
		msoReflectionType6 = 6,

		[SupportByLibrary("OF12","OF14")]
		msoReflectionType7 = 7,

		[SupportByLibrary("OF12","OF14")]
		msoReflectionType8 = 8,

		[SupportByLibrary("OF12","OF14")]
		msoReflectionType9 = 9
	}
}
