//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public enum MsoScreenSize
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoScreenSize544x376 = 0,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoScreenSize640x480 = 1,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoScreenSize720x512 = 2,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoScreenSize800x600 = 3,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoScreenSize1024x768 = 4,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoScreenSize1152x882 = 5,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoScreenSize1152x900 = 6,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoScreenSize1280x1024 = 7,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoScreenSize1600x1200 = 8,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoScreenSize1800x1440 = 9,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoScreenSize1920x1200 = 10
	}
}
