//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF14")]
	public enum MsoSmartArtNodeType
	{
		[SupportByLibrary("OF14")]
		msoSmartArtNodeTypeDefault = 1,

		[SupportByLibrary("OF14")]
		msoSmartArtNodeTypeAssistant = 2
	}
}
