//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public enum MsoShapeType
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoShapeTypeMixed = -2,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoAutoShape = 1,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoCallout = 2,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoChart = 3,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoComment = 4,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoFreeform = 5,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoGroup = 6,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoEmbeddedOLEObject = 7,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoFormControl = 8,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoLine = 9,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoLinkedOLEObject = 10,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoLinkedPicture = 11,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoOLEControlObject = 12,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoPicture = 13,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoPlaceholder = 14,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoTextEffect = 15,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoMedia = 16,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoTextBox = 17,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoScriptAnchor = 18,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoTable = 19,

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoCanvas = 20,

		[SupportByLibrary("OF10","OF11","OF12","OF14")]
		msoDiagram = 21,

		[SupportByLibrary("OF11","OF12","OF14")]
		msoInk = 22,

		[SupportByLibrary("OF11","OF12","OF14")]
		msoInkComment = 23,

		[SupportByLibrary("OF12","OF14")]
		msoSmartArt = 24,

		[SupportByLibrary("OF14")]
		msoSlicer = 25
	}
}
