//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF11","OF12","OF14")]
	public enum MsoSyncStatusType
	{
		[SupportByLibrary("OF11","OF12","OF14")]
		msoSyncStatusNoSharedWorkspace = 0,

		[SupportByLibrary("OF12","OF14")]
		msoSyncStatusNotRoaming = 0,

		[SupportByLibrary("OF11","OF12","OF14")]
		msoSyncStatusLatest = 1,

		[SupportByLibrary("OF11","OF12","OF14")]
		msoSyncStatusNewerAvailable = 2,

		[SupportByLibrary("OF11","OF12","OF14")]
		msoSyncStatusLocalChanges = 3,

		[SupportByLibrary("OF11","OF12","OF14")]
		msoSyncStatusConflict = 4,

		[SupportByLibrary("OF11","OF12","OF14")]
		msoSyncStatusSuspended = 5,

		[SupportByLibrary("OF11","OF12","OF14")]
		msoSyncStatusError = 6
	}
}
