//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum MsoTextCaps
	{
		[SupportByLibrary("OF12","OF14")]
		msoCapsMixed = -2,

		[SupportByLibrary("OF12","OF14")]
		msoNoCaps = 0,

		[SupportByLibrary("OF12","OF14")]
		msoSmallCaps = 1,

		[SupportByLibrary("OF12","OF14")]
		msoAllCaps = 2
	}
}
