//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum MsoThemeColorSchemeIndex
	{
		[SupportByLibrary("OF12","OF14")]
		msoThemeDark1 = 1,

		[SupportByLibrary("OF12","OF14")]
		msoThemeLight1 = 2,

		[SupportByLibrary("OF12","OF14")]
		msoThemeDark2 = 3,

		[SupportByLibrary("OF12","OF14")]
		msoThemeLight2 = 4,

		[SupportByLibrary("OF12","OF14")]
		msoThemeAccent1 = 5,

		[SupportByLibrary("OF12","OF14")]
		msoThemeAccent2 = 6,

		[SupportByLibrary("OF12","OF14")]
		msoThemeAccent3 = 7,

		[SupportByLibrary("OF12","OF14")]
		msoThemeAccent4 = 8,

		[SupportByLibrary("OF12","OF14")]
		msoThemeAccent5 = 9,

		[SupportByLibrary("OF12","OF14")]
		msoThemeAccent6 = 10,

		[SupportByLibrary("OF12","OF14")]
		msoThemeHyperlink = 11,

		[SupportByLibrary("OF12","OF14")]
		msoThemeFollowedHyperlink = 12
	}
}
