//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
	public enum MsoZOrderCmd
	{
		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoBringToFront = 0,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoSendToBack = 1,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoBringForward = 2,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoSendBackward = 3,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoBringInFrontOfText = 4,

		[SupportByLibrary("OF10","OF11","OF12","OF14","OF9")]
		msoSendBehindText = 5
	}
}
