//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum XlChartType
	{
		[SupportByLibrary("OF12","OF14")]
		xlColumnClustered = 51,

		[SupportByLibrary("OF12","OF14")]
		xlColumnStacked = 52,

		[SupportByLibrary("OF12","OF14")]
		xlColumnStacked100 = 53,

		[SupportByLibrary("OF12","OF14")]
		xl3DColumnClustered = 54,

		[SupportByLibrary("OF12","OF14")]
		xl3DColumnStacked = 55,

		[SupportByLibrary("OF12","OF14")]
		xl3DColumnStacked100 = 56,

		[SupportByLibrary("OF12","OF14")]
		xlBarClustered = 57,

		[SupportByLibrary("OF12","OF14")]
		xlBarStacked = 58,

		[SupportByLibrary("OF12","OF14")]
		xlBarStacked100 = 59,

		[SupportByLibrary("OF12","OF14")]
		xl3DBarClustered = 60,

		[SupportByLibrary("OF12","OF14")]
		xl3DBarStacked = 61,

		[SupportByLibrary("OF12","OF14")]
		xl3DBarStacked100 = 62,

		[SupportByLibrary("OF12","OF14")]
		xlLineStacked = 63,

		[SupportByLibrary("OF12","OF14")]
		xlLineStacked100 = 64,

		[SupportByLibrary("OF12","OF14")]
		xlLineMarkers = 65,

		[SupportByLibrary("OF12","OF14")]
		xlLineMarkersStacked = 66,

		[SupportByLibrary("OF12","OF14")]
		xlLineMarkersStacked100 = 67,

		[SupportByLibrary("OF12","OF14")]
		xlPieOfPie = 68,

		[SupportByLibrary("OF12","OF14")]
		xlPieExploded = 69,

		[SupportByLibrary("OF12","OF14")]
		xl3DPieExploded = 70,

		[SupportByLibrary("OF12","OF14")]
		xlBarOfPie = 71,

		[SupportByLibrary("OF12","OF14")]
		xlXYScatterSmooth = 72,

		[SupportByLibrary("OF12","OF14")]
		xlXYScatterSmoothNoMarkers = 73,

		[SupportByLibrary("OF12","OF14")]
		xlXYScatterLines = 74,

		[SupportByLibrary("OF12","OF14")]
		xlXYScatterLinesNoMarkers = 75,

		[SupportByLibrary("OF12","OF14")]
		xlAreaStacked = 76,

		[SupportByLibrary("OF12","OF14")]
		xlAreaStacked100 = 77,

		[SupportByLibrary("OF12","OF14")]
		xl3DAreaStacked = 78,

		[SupportByLibrary("OF12","OF14")]
		xl3DAreaStacked100 = 79,

		[SupportByLibrary("OF12","OF14")]
		xlDoughnutExploded = 80,

		[SupportByLibrary("OF12","OF14")]
		xlRadarMarkers = 81,

		[SupportByLibrary("OF12","OF14")]
		xlRadarFilled = 82,

		[SupportByLibrary("OF12","OF14")]
		xlSurface = 83,

		[SupportByLibrary("OF12","OF14")]
		xlSurfaceWireframe = 84,

		[SupportByLibrary("OF12","OF14")]
		xlSurfaceTopView = 85,

		[SupportByLibrary("OF12","OF14")]
		xlSurfaceTopViewWireframe = 86,

		[SupportByLibrary("OF12","OF14")]
		xlBubble = 15,

		[SupportByLibrary("OF12","OF14")]
		xlBubble3DEffect = 87,

		[SupportByLibrary("OF12","OF14")]
		xlStockHLC = 88,

		[SupportByLibrary("OF12","OF14")]
		xlStockOHLC = 89,

		[SupportByLibrary("OF12","OF14")]
		xlStockVHLC = 90,

		[SupportByLibrary("OF12","OF14")]
		xlStockVOHLC = 91,

		[SupportByLibrary("OF12","OF14")]
		xlCylinderColClustered = 92,

		[SupportByLibrary("OF12","OF14")]
		xlCylinderColStacked = 93,

		[SupportByLibrary("OF12","OF14")]
		xlCylinderColStacked100 = 94,

		[SupportByLibrary("OF12","OF14")]
		xlCylinderBarClustered = 95,

		[SupportByLibrary("OF12","OF14")]
		xlCylinderBarStacked = 96,

		[SupportByLibrary("OF12","OF14")]
		xlCylinderBarStacked100 = 97,

		[SupportByLibrary("OF12","OF14")]
		xlCylinderCol = 98,

		[SupportByLibrary("OF12","OF14")]
		xlConeColClustered = 99,

		[SupportByLibrary("OF12","OF14")]
		xlConeColStacked = 100,

		[SupportByLibrary("OF12","OF14")]
		xlConeColStacked100 = 101,

		[SupportByLibrary("OF12","OF14")]
		xlConeBarClustered = 102,

		[SupportByLibrary("OF12","OF14")]
		xlConeBarStacked = 103,

		[SupportByLibrary("OF12","OF14")]
		xlConeBarStacked100 = 104,

		[SupportByLibrary("OF12","OF14")]
		xlConeCol = 105,

		[SupportByLibrary("OF12","OF14")]
		xlPyramidColClustered = 106,

		[SupportByLibrary("OF12","OF14")]
		xlPyramidColStacked = 107,

		[SupportByLibrary("OF12","OF14")]
		xlPyramidColStacked100 = 108,

		[SupportByLibrary("OF12","OF14")]
		xlPyramidBarClustered = 109,

		[SupportByLibrary("OF12","OF14")]
		xlPyramidBarStacked = 110,

		[SupportByLibrary("OF12","OF14")]
		xlPyramidBarStacked100 = 111,

		[SupportByLibrary("OF12","OF14")]
		xlPyramidCol = 112,

		[SupportByLibrary("OF12","OF14")]
		xl3DColumn = -4100,

		[SupportByLibrary("OF12","OF14")]
		xlLine = 4,

		[SupportByLibrary("OF12","OF14")]
		xl3DLine = -4101,

		[SupportByLibrary("OF12","OF14")]
		xl3DPie = -4102,

		[SupportByLibrary("OF12","OF14")]
		xlPie = 5,

		[SupportByLibrary("OF12","OF14")]
		xlXYScatter = -4169,

		[SupportByLibrary("OF12","OF14")]
		xl3DArea = -4098,

		[SupportByLibrary("OF12","OF14")]
		xlArea = 1,

		[SupportByLibrary("OF12","OF14")]
		xlDoughnut = -4120,

		[SupportByLibrary("OF12","OF14")]
		xlRadar = -4151
	}
}
