//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum XlChartSplitType
	{
		[SupportByLibrary("OF12","OF14")]
		xlSplitByPosition = 1,

		[SupportByLibrary("OF12","OF14")]
		xlSplitByPercentValue = 3,

		[SupportByLibrary("OF12","OF14")]
		xlSplitByCustomSplit = 4,

		[SupportByLibrary("OF12","OF14")]
		xlSplitByValue = 2
	}
}
