//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum XlSizeRepresents
	{
		[SupportByLibrary("OF12","OF14")]
		xlSizeIsWidth = 2,

		[SupportByLibrary("OF12","OF14")]
		xlSizeIsArea = 1
	}
}
