//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum XlTickLabelPosition
	{
		[SupportByLibrary("OF12","OF14")]
		xlTickLabelPositionHigh = -4127,

		[SupportByLibrary("OF12","OF14")]
		xlTickLabelPositionLow = -4134,

		[SupportByLibrary("OF12","OF14")]
		xlTickLabelPositionNextToAxis = 4,

		[SupportByLibrary("OF12","OF14")]
		xlTickLabelPositionNone = -4142
	}
}
