//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum XlTrendlineType
	{
		[SupportByLibrary("OF12","OF14")]
		xlExponential = 5,

		[SupportByLibrary("OF12","OF14")]
		xlLinear = -4132,

		[SupportByLibrary("OF12","OF14")]
		xlLogarithmic = -4133,

		[SupportByLibrary("OF12","OF14")]
		xlMovingAvg = 6,

		[SupportByLibrary("OF12","OF14")]
		xlPolynomial = 3,

		[SupportByLibrary("OF12","OF14")]
		xlPower = 4
	}
}
