//Generated by LateBindingApi.CodeGenerator
using LateBindingApi.Core;
namespace LateBindingApi.Office.Enums
{
	[SupportByLibrary("OF12","OF14")]
	public enum XlUnderlineStyle
	{
		[SupportByLibrary("OF12","OF14")]
		xlUnderlineStyleDouble = -4119,

		[SupportByLibrary("OF12","OF14")]
		xlUnderlineStyleDoubleAccounting = 5,

		[SupportByLibrary("OF12","OF14")]
		xlUnderlineStyleNone = -4142,

		[SupportByLibrary("OF12","OF14")]
		xlUnderlineStyleSingle = 2,

		[SupportByLibrary("OF12","OF14")]
		xlUnderlineStyleSingleAccounting = 4
	}
}
