//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Excel
{
	[SupportByLibrary("XL10","XL11","XL12","XL14")]
	public class CalculatedMember : COMObject
	{
		#region Construction

		public CalculatedMember(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public CalculatedMember(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public CalculatedMember(COMObject replacedObject) : base(replacedObject)
		{
		}

		public CalculatedMember()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public LateBindingApi.Excel.Application Application
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Application");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.Application newClass = new LateBindingApi.Excel.Application(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public LateBindingApi.Excel.Enums.XlCreator Creator
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Creator");
				return (LateBindingApi.Excel.Enums.XlCreator)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public string Name
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Name");
				return (string)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public string Formula
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Formula");
				return (string)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public string SourceName
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "SourceName");
				return (string)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public Int32 SolveOrder
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "SolveOrder");
				return (Int32)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public bool IsValid
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "IsValid");
				return (bool)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public string _Default
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "_Default");
				return (string)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public LateBindingApi.Excel.Enums.XlCalculatedMemberType Type
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Type");
				return (LateBindingApi.Excel.Enums.XlCalculatedMemberType)returnValue;
			}
		}

		[SupportByLibrary("XL14")]
		public bool Dynamic
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Dynamic");
				return (bool)returnValue;
			}
		}

		[SupportByLibrary("XL14")]
		public string DisplayFolder
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "DisplayFolder");
				return (string)returnValue;
			}
		}

		[SupportByLibrary("XL14")]
		public bool HierarchizeDistinct
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "HierarchizeDistinct");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "HierarchizeDistinct", value);
			}						
		}


		[SupportByLibrary("XL14")]
		public bool FlattenHierarchies
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "FlattenHierarchies");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "FlattenHierarchies", value);
			}						
		}


		#endregion

		#region Methods

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public void Delete()
		{
			Invoker.Method(this, "Delete", null);
		}

		#endregion

	}
}
