//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Excel
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public class FillFormat : LateBindingApi.Office._IMsoDispObj
	{
		#region Construction

		public FillFormat(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public FillFormat(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public FillFormat(COMObject replacedObject) : base(replacedObject)
		{
		}

		public FillFormat()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.ColorFormat BackColor
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "BackColor");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.ColorFormat newClass = new LateBindingApi.Excel.ColorFormat(this, returnValue);
				return newClass;
			}
			set
			{
				Invoker.PropertySet(this, "BackColor", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.ColorFormat ForeColor
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "ForeColor");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.ColorFormat newClass = new LateBindingApi.Excel.ColorFormat(this, returnValue);
				return newClass;
			}
			set
			{
				Invoker.PropertySet(this, "ForeColor", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Office.Enums.MsoGradientColorType GradientColorType
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "GradientColorType");
				return (LateBindingApi.Office.Enums.MsoGradientColorType)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Double GradientDegree
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "GradientDegree");
				return (Double)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Office.Enums.MsoGradientStyle GradientStyle
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "GradientStyle");
				return (LateBindingApi.Office.Enums.MsoGradientStyle)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Int32 GradientVariant
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "GradientVariant");
				return (Int32)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Office.Enums.MsoPatternType Pattern
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Pattern");
				return (LateBindingApi.Office.Enums.MsoPatternType)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Office.Enums.MsoPresetGradientType PresetGradientType
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "PresetGradientType");
				return (LateBindingApi.Office.Enums.MsoPresetGradientType)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Office.Enums.MsoPresetTexture PresetTexture
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "PresetTexture");
				return (LateBindingApi.Office.Enums.MsoPresetTexture)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public string TextureName
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "TextureName");
				return (string)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Office.Enums.MsoTextureType TextureType
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "TextureType");
				return (LateBindingApi.Office.Enums.MsoTextureType)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Double Transparency
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Transparency");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Transparency", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Office.Enums.MsoFillType Type
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Type");
				return (LateBindingApi.Office.Enums.MsoFillType)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Office.Enums.MsoTriState Visible
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Visible");
				return (LateBindingApi.Office.Enums.MsoTriState)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Visible", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Office.GradientStops GradientStops
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "GradientStops");
				if(null == returnValue)
					return null;
				LateBindingApi.Office.GradientStops newClass = new LateBindingApi.Office.GradientStops(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL12","XL14")]
		public Double TextureOffsetX
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "TextureOffsetX");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "TextureOffsetX", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public Double TextureOffsetY
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "TextureOffsetY");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "TextureOffsetY", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Office.Enums.MsoTextureAlignment TextureAlignment
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "TextureAlignment");
				return (LateBindingApi.Office.Enums.MsoTextureAlignment)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "TextureAlignment", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public Double TextureHorizontalScale
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "TextureHorizontalScale");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "TextureHorizontalScale", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public Double TextureVerticalScale
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "TextureVerticalScale");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "TextureVerticalScale", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Office.Enums.MsoTriState TextureTile
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "TextureTile");
				return (LateBindingApi.Office.Enums.MsoTriState)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "TextureTile", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Office.Enums.MsoTriState RotateWithObject
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "RotateWithObject");
				return (LateBindingApi.Office.Enums.MsoTriState)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "RotateWithObject", value);
			}						
		}


		[SupportByLibrary("XL14")]
		public LateBindingApi.Office.PictureEffects PictureEffects
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "PictureEffects");
				if(null == returnValue)
					return null;
				LateBindingApi.Office.PictureEffects newClass = new LateBindingApi.Office.PictureEffects(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL14")]
		public Double GradientAngle
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "GradientAngle");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "GradientAngle", value);
			}						
		}


		#endregion

		#region Methods

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public void Background()
		{
			Invoker.Method(this, "Background", null);
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public void OneColorGradient(LateBindingApi.Office.Enums.MsoGradientStyle style, Int32 variant, Double degree)
		{
			object[] paramArray = new object[3];
			paramArray[0] = style;
			paramArray[1] = variant;
			paramArray[2] = degree;
			Invoker.Method(this, "OneColorGradient", paramArray);
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public void Patterned(LateBindingApi.Office.Enums.MsoPatternType pattern)
		{
			object[] paramArray = new object[1];
			paramArray[0] = pattern;
			Invoker.Method(this, "Patterned", paramArray);
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public void PresetGradient(LateBindingApi.Office.Enums.MsoGradientStyle style, Int32 variant, LateBindingApi.Office.Enums.MsoPresetGradientType presetGradientType)
		{
			object[] paramArray = new object[3];
			paramArray[0] = style;
			paramArray[1] = variant;
			paramArray[2] = presetGradientType;
			Invoker.Method(this, "PresetGradient", paramArray);
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public void PresetTextured(LateBindingApi.Office.Enums.MsoPresetTexture presetTexture)
		{
			object[] paramArray = new object[1];
			paramArray[0] = presetTexture;
			Invoker.Method(this, "PresetTextured", paramArray);
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public void Solid()
		{
			Invoker.Method(this, "Solid", null);
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public void TwoColorGradient(LateBindingApi.Office.Enums.MsoGradientStyle style, Int32 variant)
		{
			object[] paramArray = new object[2];
			paramArray[0] = style;
			paramArray[1] = variant;
			Invoker.Method(this, "TwoColorGradient", paramArray);
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public void UserPicture(string pictureFile)
		{
			object[] paramArray = new object[1];
			paramArray[0] = pictureFile;
			Invoker.Method(this, "UserPicture", paramArray);
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public void UserTextured(string textureFile)
		{
			object[] paramArray = new object[1];
			paramArray[0] = textureFile;
			Invoker.Method(this, "UserTextured", paramArray);
		}

		#endregion

	}
}
