//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Excel
{
	[SupportByLibrary("XL11","XL12","XL14")]
	public class ListDataFormat : COMObject
	{
		#region Construction

		public ListDataFormat(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public ListDataFormat(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public ListDataFormat(COMObject replacedObject) : base(replacedObject)
		{
		}

		public ListDataFormat()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("XL11","XL12","XL14")]
		public LateBindingApi.Excel.Application Application
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Application");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.Application newClass = new LateBindingApi.Excel.Application(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL11","XL12","XL14")]
		public LateBindingApi.Excel.Enums.XlCreator Creator
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Creator");
				return (LateBindingApi.Excel.Enums.XlCreator)returnValue;
			}
		}

		[SupportByLibrary("XL11","XL12","XL14")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL11","XL12","XL14")]
		public LateBindingApi.Excel.Enums.XlListDataType _Default
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "_Default");
				return (LateBindingApi.Excel.Enums.XlListDataType)returnValue;
			}
		}

		[SupportByLibrary("XL11","XL12","XL14")]
		public COMVariant Choices
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Choices");
				COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL11","XL12","XL14")]
		public Int32 DecimalPlaces
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "DecimalPlaces");
				return (Int32)returnValue;
			}
		}

		[SupportByLibrary("XL11","XL12","XL14")]
		public COMVariant DefaultValue
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "DefaultValue");
				COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL11","XL12","XL14")]
		public bool IsPercent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "IsPercent");
				return (bool)returnValue;
			}
		}

		[SupportByLibrary("XL11","XL12","XL14")]
		public Int32 lcid
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "lcid");
				return (Int32)returnValue;
			}
		}

		[SupportByLibrary("XL11","XL12","XL14")]
		public Int32 MaxCharacters
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MaxCharacters");
				return (Int32)returnValue;
			}
		}

		[SupportByLibrary("XL11","XL12","XL14")]
		public COMVariant MaxNumber
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MaxNumber");
				COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL11","XL12","XL14")]
		public COMVariant MinNumber
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MinNumber");
				COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL11","XL12","XL14")]
		public bool Required
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Required");
				return (bool)returnValue;
			}
		}

		[SupportByLibrary("XL11","XL12","XL14")]
		public LateBindingApi.Excel.Enums.XlListDataType Type
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Type");
				return (LateBindingApi.Excel.Enums.XlListDataType)returnValue;
			}
		}

		[SupportByLibrary("XL11","XL12","XL14")]
		public bool ReadOnly
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "ReadOnly");
				return (bool)returnValue;
			}
		}

		[SupportByLibrary("XL11","XL12","XL14")]
		public bool AllowFillIn
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "AllowFillIn");
				return (bool)returnValue;
			}
		}

		#endregion

		#region Methods

		#endregion

	}
}
