//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Excel
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public class Outline : COMObject
	{
		#region Construction

		public Outline(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public Outline(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public Outline(COMObject replacedObject) : base(replacedObject)
		{
		}

		public Outline()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Application Application
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Application");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.Application newClass = new LateBindingApi.Excel.Application(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Enums.XlCreator Creator
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Creator");
				return (LateBindingApi.Excel.Enums.XlCreator)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public bool AutomaticStyles
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "AutomaticStyles");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "AutomaticStyles", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Enums.XlSummaryColumn SummaryColumn
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "SummaryColumn");
				return (LateBindingApi.Excel.Enums.XlSummaryColumn)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "SummaryColumn", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Enums.XlSummaryRow SummaryRow
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "SummaryRow");
				return (LateBindingApi.Excel.Enums.XlSummaryRow)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "SummaryRow", value);
			}						
		}


		#endregion

		#region Methods

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMVariant ShowLevels()
		{
			object returnValue = Invoker.MethodReturn(this, "ShowLevels", null);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMVariant ShowLevels(object rowLevels, object columnLevels)
		{
			object[] paramArray = new object[2];
			paramArray[0] = rowLevels;
			paramArray[1] = columnLevels;
			object returnValue = Invoker.MethodReturn(this, "ShowLevels", paramArray);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		#endregion

	}
}
