//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Excel
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public class Point : COMObject
	{
		#region Construction

		public Point(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public Point(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public Point(COMObject replacedObject) : base(replacedObject)
		{
		}

		public Point()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Application Application
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Application");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.Application newClass = new LateBindingApi.Excel.Application(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Enums.XlCreator Creator
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Creator");
				return (LateBindingApi.Excel.Enums.XlCreator)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Border Border
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Border");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.Border newClass = new LateBindingApi.Excel.Border(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.DataLabel DataLabel
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "DataLabel");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.DataLabel newClass = new LateBindingApi.Excel.DataLabel(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Int32 Explosion
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Explosion");
				return (Int32)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Explosion", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public bool HasDataLabel
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "HasDataLabel");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "HasDataLabel", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Interior Interior
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Interior");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.Interior newClass = new LateBindingApi.Excel.Interior(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public bool InvertIfNegative
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "InvertIfNegative");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "InvertIfNegative", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Int32 MarkerBackgroundColor
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MarkerBackgroundColor");
				return (Int32)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MarkerBackgroundColor", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Enums.XlColorIndex MarkerBackgroundColorIndex
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MarkerBackgroundColorIndex");
				return (LateBindingApi.Excel.Enums.XlColorIndex)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MarkerBackgroundColorIndex", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Int32 MarkerForegroundColor
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MarkerForegroundColor");
				return (Int32)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MarkerForegroundColor", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Enums.XlColorIndex MarkerForegroundColorIndex
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MarkerForegroundColorIndex");
				return (LateBindingApi.Excel.Enums.XlColorIndex)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MarkerForegroundColorIndex", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Int32 MarkerSize
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MarkerSize");
				return (Int32)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MarkerSize", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Enums.XlMarkerStyle MarkerStyle
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MarkerStyle");
				return (LateBindingApi.Excel.Enums.XlMarkerStyle)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MarkerStyle", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Enums.XlChartPictureType PictureType
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "PictureType");
				return (LateBindingApi.Excel.Enums.XlChartPictureType)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "PictureType", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Int32 PictureUnit
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "PictureUnit");
				return (Int32)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "PictureUnit", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public bool ApplyPictToSides
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "ApplyPictToSides");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "ApplyPictToSides", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public bool ApplyPictToFront
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "ApplyPictToFront");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "ApplyPictToFront", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public bool ApplyPictToEnd
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "ApplyPictToEnd");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "ApplyPictToEnd", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public bool Shadow
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Shadow");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Shadow", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public bool SecondaryPlot
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "SecondaryPlot");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "SecondaryPlot", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.ChartFillFormat Fill
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Fill");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.ChartFillFormat newClass = new LateBindingApi.Excel.ChartFillFormat(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL12","XL14")]
		public bool Has3DEffect
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Has3DEffect");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Has3DEffect", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public Double PictureUnit2
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "PictureUnit2");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "PictureUnit2", value);
			}						
		}


		[SupportByLibrary("XL12","XL14")]
		public LateBindingApi.Excel.ChartFormat Format
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Format");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.ChartFormat newClass = new LateBindingApi.Excel.ChartFormat(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL14")]
		public Double Height
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Height");
				return (Double)returnValue;
			}
		}

		[SupportByLibrary("XL14")]
		public Double Width
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Width");
				return (Double)returnValue;
			}
		}

		[SupportByLibrary("XL14")]
		public Double Top
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Top");
				return (Double)returnValue;
			}
		}

		[SupportByLibrary("XL14")]
		public Double Left
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Left");
				return (Double)returnValue;
			}
		}

		[SupportByLibrary("XL14")]
		public string Name
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Name");
				return (string)returnValue;
			}
		}

		#endregion

		#region Methods

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMVariant ApplyDataLabels(LateBindingApi.Excel.Enums.XlDataLabelsType type)
		{
			object[] paramArray = new object[1];
			paramArray[0] = type;
			object returnValue = Invoker.MethodReturn(this, "ApplyDataLabels", paramArray);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		[SupportByLibrary("XL9")]
		public COMVariant ApplyDataLabels(LateBindingApi.Excel.Enums.XlDataLabelsType type, object legendKey, object autoText)
		{
			object[] paramArray = new object[3];
			paramArray[0] = type;
			paramArray[1] = legendKey;
			paramArray[2] = autoText;
			object returnValue = Invoker.MethodReturn(this, "ApplyDataLabels", paramArray);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14")]
		public COMVariant ApplyDataLabels(LateBindingApi.Excel.Enums.XlDataLabelsType type, object legendKey, object autoText, object hasLeaderLines, object showSeriesName, object showCategoryName, object showValue, object showPercentage, object showBubbleSize, object separator)
		{
			object[] paramArray = new object[10];
			paramArray[0] = type;
			paramArray[1] = legendKey;
			paramArray[2] = autoText;
			paramArray[3] = hasLeaderLines;
			paramArray[4] = showSeriesName;
			paramArray[5] = showCategoryName;
			paramArray[6] = showValue;
			paramArray[7] = showPercentage;
			paramArray[8] = showBubbleSize;
			paramArray[9] = separator;
			object returnValue = Invoker.MethodReturn(this, "ApplyDataLabels", paramArray);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMVariant ClearFormats()
		{
			object returnValue = Invoker.MethodReturn(this, "ClearFormats", null);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMVariant Copy()
		{
			object returnValue = Invoker.MethodReturn(this, "Copy", null);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMVariant Delete()
		{
			object returnValue = Invoker.MethodReturn(this, "Delete", null);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMVariant Paste()
		{
			object returnValue = Invoker.MethodReturn(this, "Paste", null);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMVariant Select()
		{
			object returnValue = Invoker.MethodReturn(this, "Select", null);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		[SupportByLibrary("XL11","XL12","XL14")]
		public COMVariant _ApplyDataLabels(LateBindingApi.Excel.Enums.XlDataLabelsType type)
		{
			object[] paramArray = new object[1];
			paramArray[0] = type;
			object returnValue = Invoker.MethodReturn(this, "_ApplyDataLabels", paramArray);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		[SupportByLibrary("XL11","XL12","XL14")]
		public COMVariant _ApplyDataLabels(LateBindingApi.Excel.Enums.XlDataLabelsType type, object legendKey, object autoText, object hasLeaderLines)
		{
			object[] paramArray = new object[4];
			paramArray[0] = type;
			paramArray[1] = legendKey;
			paramArray[2] = autoText;
			paramArray[3] = hasLeaderLines;
			object returnValue = Invoker.MethodReturn(this, "_ApplyDataLabels", paramArray);
			COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
			return returnObject;
		}

		[SupportByLibrary("XL14")]
		public Double PieSliceLocation(LateBindingApi.Excel.Enums.XlPieSliceLocation loc, LateBindingApi.Excel.Enums.XlPieSliceIndex index)
		{
			object[] paramArray = new object[2];
			paramArray[0] = loc;
			paramArray[1] = index;
			object returnValue = Invoker.MethodReturn(this, "PieSliceLocation", paramArray);
			return (Double)returnValue;
		}

		#endregion

	}
}
