//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Excel
{
	[SupportByLibrary("XL14")]
	public class SlicerItem : COMObject
	{
		#region Construction

		public SlicerItem(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public SlicerItem(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public SlicerItem(COMObject replacedObject) : base(replacedObject)
		{
		}

		public SlicerItem()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("XL14")]
		public LateBindingApi.Excel.Application Application
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Application");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.Application newClass = new LateBindingApi.Excel.Application(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL14")]
		public LateBindingApi.Excel.Enums.XlCreator Creator
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Creator");
				return (LateBindingApi.Excel.Enums.XlCreator)returnValue;
			}
		}

		[SupportByLibrary("XL14")]
		public LateBindingApi.Excel.SlicerCache Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.SlicerCache newClass = new LateBindingApi.Excel.SlicerCache(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL14")]
		public string Caption
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Caption");
				return (string)returnValue;
			}
		}

		[SupportByLibrary("XL14")]
		public string Name
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Name");
				return (string)returnValue;
			}
		}

		[SupportByLibrary("XL14")]
		public COMVariant SourceName
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "SourceName");
				COMVariant returnObject = LateBindingApi.Core.Factory.CreateVariantFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL14")]
		public string SourceNameStandard
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "SourceNameStandard");
				return (string)returnValue;
			}
		}

		[SupportByLibrary("XL14")]
		public string Value
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Value");
				return (string)returnValue;
			}
		}

		[SupportByLibrary("XL14")]
		public bool Selected
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Selected");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Selected", value);
			}						
		}


		[SupportByLibrary("XL14")]
		public bool HasData
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "HasData");
				return (bool)returnValue;
			}
		}

		#endregion

		#region Methods

		#endregion

	}
}
