//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.Excel
{
	[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
	public class TextFrame : COMObject
	{
		#region Construction

		public TextFrame(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public TextFrame(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public TextFrame(COMObject replacedObject) : base(replacedObject)
		{
		}

		public TextFrame()
		{
		}

		#endregion

		#region Properties

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Application Application
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Application");
				if(null == returnValue)
					return null;
				LateBindingApi.Excel.Application newClass = new LateBindingApi.Excel.Application(this, returnValue);
				return newClass;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Enums.XlCreator Creator
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Creator");
				return (LateBindingApi.Excel.Enums.XlCreator)returnValue;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public COMObject Parent
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Parent");
				COMObject returnObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this, returnValue);
				return returnObject;
			}
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Double MarginBottom
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MarginBottom");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MarginBottom", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Double MarginLeft
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MarginLeft");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MarginLeft", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Double MarginRight
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MarginRight");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MarginRight", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Double MarginTop
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "MarginTop");
				return (Double)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "MarginTop", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Office.Enums.MsoTextOrientation Orientation
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "Orientation");
				return (LateBindingApi.Office.Enums.MsoTextOrientation)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "Orientation", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Enums.XlHAlign HorizontalAlignment
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "HorizontalAlignment");
				return (LateBindingApi.Excel.Enums.XlHAlign)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "HorizontalAlignment", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Enums.XlVAlign VerticalAlignment
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "VerticalAlignment");
				return (LateBindingApi.Excel.Enums.XlVAlign)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "VerticalAlignment", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public bool AutoSize
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "AutoSize");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "AutoSize", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public Int32 ReadingOrder
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "ReadingOrder");
				return (Int32)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "ReadingOrder", value);
			}						
		}


		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public bool AutoMargins
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "AutoMargins");
				return (bool)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "AutoMargins", value);
			}						
		}


		[SupportByLibrary("XL14")]
		public LateBindingApi.Excel.Enums.XlOartVerticalOverflow VerticalOverflow
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "VerticalOverflow");
				return (LateBindingApi.Excel.Enums.XlOartVerticalOverflow)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "VerticalOverflow", value);
			}						
		}


		[SupportByLibrary("XL14")]
		public LateBindingApi.Excel.Enums.XlOartHorizontalOverflow HorizontalOverflow
		{
			get
			{
				object returnValue = Invoker.PropertyGet(this, "HorizontalOverflow");
				return (LateBindingApi.Excel.Enums.XlOartHorizontalOverflow)returnValue;
			}
			set
			{
				Invoker.PropertySet(this, "HorizontalOverflow", value);
			}						
		}


		#endregion

		#region Methods

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Characters Characters()
		{
			object returnValue = Invoker.MethodReturn(this, "Characters", null);
			if(null == returnValue)
				return null;
			LateBindingApi.Excel.Characters newClass = new LateBindingApi.Excel.Characters(this, returnValue);
			return newClass;
		}

		[SupportByLibrary("XL10","XL11","XL12","XL14","XL9")]
		public LateBindingApi.Excel.Characters Characters(object start, object length)
		{
			object[] paramArray = new object[2];
			paramArray[0] = start;
			paramArray[1] = length;
			object returnValue = Invoker.MethodReturn(this, "Characters", paramArray);
			if(null == returnValue)
				return null;
			LateBindingApi.Excel.Characters newClass = new LateBindingApi.Excel.Characters(this, returnValue);
			return newClass;
		}

		#endregion

	}
}
