//Generated by LateBindingApi.CodeGenerator
using System;
using System.Reflection;
using System.ComponentModel;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.stdole
{
	[SupportByLibrary("OLE")]
	public class Font : COMObject
	{
		#region Construction

		public Font(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}

		public Font(COMObject parentObject, object comProxy, Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}

		public Font(COMObject replacedObject) : base(replacedObject)
		{
		}

		public Font()
		{
		}

		#endregion

		#region Properties

		#endregion

		#region Methods

		#endregion

	}
}
